zeek/spicy

doc/Makefile
doc/conf.py
doc/zeek.rst
hilti/src/base/util.cc

These changes are required for e.g., building the docs with readthedocs.

Tweak docs so they can be built without a build tree

---

doc/Makefile

This fixes the build task on `gcc9_ubuntu_release_no_jit_task`.

Build documentation from original doc folder

---

ci/run-ci
doc/Makefile
doc/conf.py
doc/index.rst
doc/installation.rst

This PR fixes broken links in documentation and a `check` target to `doc/Makefile`. We execute `check` when building documentation in CI.

Fix broken doc links

---

hilti/include/ast/expressions/all.h
hilti/include/ast/expressions/grouping.h
hilti/include/ast/nodes.decl
hilti/include/rt/compiler-setup.h
hilti/src/compiler/codegen/expressions.cc
hilti/src/compiler/parser/parser.yy
hilti/src/compiler/visitors/printer.cc
spicy/src/compiler/parser/parser.yy
tests/Baseline/hilti.ast.validation/output

While so far we did capture the priority of subexpressions inside the
AST, the generated C++ would roll them out flat without considering
C++ operator precendence. Now we pass parentheses through from the
source code to the generated code to preserve priorities.
Closes #225.

Preserve parentheses inside expressions.

---

hilti/src/compiler/parser/parser.yy
spicy/src/compiler/parser/parser.yy
tests/spicy/types/integer/plus-zero.spicy

It used to create an unsigned integer.
Closes #170.

Change "+<int>" to create a signed integer value.

---

hilti/include/base/util.h
hilti/include/rt/util.h
hilti/src/compiler/codegen/ctors.cc
hilti/src/rt/util.cc
hilti/tests/util.cc

Turns out we can't just encode non-printable characters as \xNN
because C++ compilers look for more than 2 digits when decoding
"\x...". Now using octal \NNN instead, that's always 3 digits.
Closes #217.

Fix generation of escaped C++ string literals.

---

doc/conf.py

We check links during the `build` phase, but generate package artifacts
in a follow-up step. If for some reason package artifacts are absent in
Cirrus CI's artifact cache, this can lead to situations where the link
check fails and we never repopulate the artifacts.
For now just ignore links to the artifacts when performing the
documentation link check.

Ignore package links in documentation linkcheck.

---

doc/Makefile

Sphinx' linkcheck can be pretty noisy in that it outputs all checked
links alongside their status. This can make it hard to quickly grap what
might be an issue, especially since error log lines might already be off
the screen.
This patch makes the command silent by default only showing errors, but
not warnings.

Suppress any output from doc's `make check` by default.

---

doc/programming/parsing.rst
hilti/src/compiler/codegen/types.cc
hilti/src/compiler/visitors/coercer.cc

These were added while cleaning up `Result` in some older version and should have never landed.

Remove outdated FIXMEs

---

hilti/CMakeLists.txt
hilti/include/rt/iterator.h
hilti/include/rt/types/vector.h
hilti/src/rt/tests/vector.cc

This branch introduces a first set of unit tests for `rt::Vector` member
functions, and performs some cleanups.

First pass over rt::Vector

---

hilti/CMakeLists.txt
hilti/include/ast/builder/type.h
hilti/include/ast/ctors/list.h
hilti/include/ast/ctors/map.h
hilti/include/ast/ctors/set.h
hilti/include/ast/ctors/vector.h
hilti/src/ast/builder/type.cc
hilti/src/compiler/visitors/apply-coercions.cc
hilti/src/compiler/visitors/validator.cc
tests/Baseline/hilti.types.list.ctor-fail/output
tests/Baseline/hilti.types.map.ctor-fail/output
tests/Baseline/hilti.types.set.ctor-fail/output
tests/Baseline/hilti.types.vector.ctor-fail/output
tests/hilti/types/list/ctor-fail.hlt
tests/hilti/types/list/ctor.hlt
tests/hilti/types/map/ctor-fail.hlt
tests/hilti/types/map/ctor.hlt
tests/hilti/types/set/ctor-fail.hlt
tests/hilti/types/set/ctor.hlt
tests/hilti/types/vector/ctor.hlt

For a list constructor [x_1,...,x_n], we used to take the type of the
first element as the list's element type. Now we check all elements if
their types match; only if so, we use that type. Otherwise we treat
the element type as unknown, which may then lead to validation errors.
We also unify this logic across the list/map/set constructors,
although map/set did already have custom validation logic to catch
type mismatches.
Closes #196.

Reject lists with inconsistent types.

---

docker/Makefile

This patch changes `docker/Makefile` so that the Docker Hub password is
not passed on the command line anymore which could be inspected by
anyone with access to process table of the machine the job is running.
Instead we now read the password from a file and pass it via a pipe into
the login command.

Avoid leaking passwords into command lines in `docker/Makefile`.

---

doc/autogen/types/bytes.rst
hilti/include/ast/operators/bytes.h
tests/hilti/types/bytes/decode.hlt

Make UTF8 default for bytes::decode().

---

hilti/include/ast/declarations/all.h
hilti/include/ast/declarations/imported-module.h
hilti/include/ast/declarations/module.h
hilti/include/ast/nodes.decl
hilti/src/ast/scope.cc
hilti/src/compiler/unit.cc
hilti/src/compiler/visitors/scope-builder.cc
hilti/src/compiler/visitors/validator.cc
hilti/src/global.cc
tests/Baseline/hilti.ast.basic-module/output
tests/Baseline/hilti.ast.coercion/output
tests/Baseline/hilti.ast.imported-id/output
tests/Baseline/hilti.ast.types/output

Normally all scope entries should be pointing to declarations, but we
made an exception for "Module", which was inserted into the scope
directly. This commit introduces a separate "declaration::Module"
wrapper so that we can insert that into the scope, avoiding that
exception.
With that in place, we can then easily catch if an ID refers directly
to a module, which has no use case.
For the record: I did consider removing the current "Module" node
class altogether, and simply replacing it with "declaration::Module".
However, "Module" is special in that it's our only mutable AST node,
and it didn't feel right to mix that in with the other, non-mutable
declarations.
Closes #248.

Fix AST inconsistency with how modules were stored in scopes.

---

hilti/src/rt/tests/bytes.cc
hilti/src/rt/tests/stream.cc
hilti/src/rt/types/stream.cc

Properly escape data when stringifying streams

---

docker/Makefile

This patch fixes two errors in `docker/Makefile`:
- correctly terminated a quoted string
- fix control flow for error exit on missing Docker password file

Fix shell commands in `docker/Makefile`.

---

zeek/compiler/glue-compiler.cc
zeek/compiler/glue-compiler.h
zeek/plugin/lib/protocols/tftp.evt

The fix is quite involved because the parser is really just a hack
right now, and we need to add state machine to track whether we are
inside a comment. We need to switch to a flex/bison parser here
eventually.
We use new comments inside tftp.evt as our test, that used to be not
working.
Closes #312.

Fix comment parsing in EVT files.

---

doc/autogen/spicy-functions.spicy
hilti/CMakeLists.txt
hilti/include/rt/util.h
hilti/src/rt/tests/util.cc
hilti/src/rt/util.cc
spicy/lib/spicy.spicy
tests/btest.cfg
tests/spicy/rt/strftime.spicy

This function is exposed in Spicy as `strftime`.
Closes #237.

Add `strftime` to `hilti::rt`.

---

zeek/CMakeLists.txt
zeek/compiler/CMakeLists.txt
zeek/compiler/debug.h
zeek/plugin/CMakeLists.txt
zeek/plugin/include/zeek-reporter.h
zeek/plugin/src/plugin-jit.cc
zeek/plugin/src/plugin.cc

- Fix include path
- Build spicyz even if no JIT support is available (it can still generate C++ code).
- Remove some unnecessary dependencies on HILTI/Spicy libs on plugin code

Fix JIT-less build of Zeek plugin.

---

tests/Baseline/zeek.lib.protocols.http/output
tests/zeek/lib/protocols/http.zeek
zeek/plugin/lib/protocols/http.evt
zeek/plugin/lib/protocols/zeek_http.spicy

The event isn't used anywhere by default in Zeek, but it's a nice
example of transforming Spicy information on the fly to match a
Zeek-side event signature.
#335

Add http_all_headers() event to HTTP EVT file.

---

doc/Makefile

Closes #282.
@bbannier Will this work with CI? (Don't remember what the earlier change there was)

Set PATH when building documation so that we find the Spicy tools.

---

zeek/compiler/glue-compiler.cc
zeek/plugin/include/runtime-support.h
zeek/plugin/spicy/zeek_rt.hlt
zeek/plugin/src/runtime-support.cc

The check we already had for this came to late.
Skipping a test, as it would require a full compiler cycle + Zeek
execution to trigger the error message.
Closes #365.

Zeek plugin: Catch if more parameters are given than Zeek expects.

---

3rdparty/justrx/CMakeLists.txt
3rdparty/justrx/test/CMakeLists.txt
cmake/FindClangJIT.cmake
hilti/CMakeLists.txt
spicy/CMakeLists.txt
zeek/CMakeLists.txt
zeek/compiler/CMakeLists.txt
zeek/plugin/CMakeLists.txt

If Spicy headers were already installed into a path somewhere in the
include lookup, we could have found the same header twice, preferring
the installed header over the one of the current checkout. This could
have lead to diagnostics about duplicate definitions since due to use of
`#pragma once` in our headers the compiler would not have detected that
a header was already included (and even if it would have detected this,
it would have included the incorrect header).
This patch adds include paths from the current checkout before any
system paths.
Closes #274.

Unbreak build for when other Spicy headers are already installed.

---

spicy/CMakeLists.txt

This would have triggered an error when building with `HILTI_USE_JIT`.
Closes #398.

Remove duplicate spicy-driver CMake target.

---

doc/getting-started.rst

Use the file that we put our example HTTP parser in,
just as with the other shell commands above and below.

Fix filename in getting started docs

---

hilti/include/compiler/coercion.h
hilti/include/compiler/plugin.h
hilti/include/rt/result.h
hilti/src/compiler/clang.cc
hilti/src/compiler/driver.cc
hilti/src/rt/tests/result.cc
spicy/tests/grammar.cc

`rt::Result` did provide implicit conversions to `bool`, but e.g., no
operators for `==` or `!=` so that Due to the language rules any (not)
equality check of `rt::Result` was performed by first converting both
operands to `bool` and then comparing them. Since `rt::Result`'s
bool conversion is just intended to check whether it has a value (a
typical use in conditionals), equality comparisions also just checked
whether both the operands had the same value state (both value, or both
error state). This is not what is intended.
This patch makes the conversion of `rt::Result` to `bool` `explicit`;
with that we can still use `rt::Result`s in conditionals, but disallow
unintended conversions. We also fix the code so that it now
- explicitly converts to bool where needed
- actually stringifies …

Remove unintended conversion of `rt::Result` to `bool`.

---

.cirrus.yml
ci/run-ci
cmake/Util.cmake
hilti/CMakeLists.txt
hilti/include/compiler/detail/clang.h
hilti/include/compiler/jit.h
hilti/include/compiler/plugin.h
hilti/src/compiler/clang.cc
hilti/src/compiler/driver.cc
hilti/src/compiler/jit.cc
hilti/src/compiler/plugin.cc
spicy/CMakeLists.txt
spicy/bin/spicy-doc.cc
spicy/bin/spicy-dump/CMakeLists.txt
spicy/src/compiler/plugin.cc
zeek/CMakeLists.txt
zeek/plugin/CMakeLists.txt

The binaries weren't pulling in the Spicy plugin because the linker
didn't see any of its symbols referenced and would just strip it all
out, including the global constructor. Even when I forced my way
around that, the same problem would show up in other ways: other
constructors now missing, and runtime functions not being included
because a binary would seemingly not make use of them.
I now fixed that in a similar way as we already do for the runtime
libraries: using object libraries instead of static libraries. That
seems the way to go with CMake. So if the build is configured for
static libraries, we now link our binaries against separately defined
object versions of libhilti and libspicy. That makes sure everything
gets included. We still build the actual static libraries as well for …

Fix build with static libraries.

---

zeek/plugin/include/runtime-support.h
zeek/plugin/src/file-analyzer.cc
zeek/plugin/src/plugin-jit.cc
zeek/plugin/src/plugin.cc
zeek/plugin/src/protocol-analyzer.cc
zeek/plugin/src/runtime-support.cc

This PR makes some simple changes that fix problems with building against Zeek's master branch. https://github.com/zeek/zeek/pull/1066 is a corresponding PR on the Zeek side that fixes a number of related issues that are causing Spicy builds to fail.
The only issue that this does not fix is the usage of versions of `ConnectionEstablished` and `ConnectionFinished` that take `int` arguments in zeek/plugin/include/protocol-analyzer.h. These methods were changed in Zeek to take `bool` arguments, but deprecated versions of them were not added (because virtual methods aren't flagged as deprecated when overridden anwyays). A NEWS entry for Zeek indicates that this is a breaking change, and Spicy should be updated to use those when appropriate.

Fix some build failures from building against Zeek 3.2 dev versions

---

configure
hilti/include/config.h.in
hilti/src/compiler/clang.cc
hilti/src/config.cc.in

They weren't used consistently already. If needed, set CXX_FLAGS
instead during configure, e.g.:
CXXFLAGS="-isystem /opt/rh/devtoolset-9/root/usr/include/c++/9" ./configure ...
Closes #423.

Remove C{,XX}_SYSTEM_INCLUDE_DIRS cmake flags.

---

spicy/src/compiler/codegen/parser-builder.cc
tests/Baseline/spicy.rt.base64-filter-eod/output
tests/spicy/rt/base64-filter-eod.spicy

End-of-input would not always be carried through to units that had
their inputs filtered.

Fix missing filter end-of-input signal.

---

hilti/CMakeLists.txt
hilti/include/rt/types/time.h
hilti/include/rt/types/union.h
hilti/src/rt/tests/struct.cc
hilti/src/rt/tests/time.cc
hilti/src/rt/tests/to_string.cc
hilti/src/rt/tests/union.cc

This patch is part of #468 and covers `types/string.h`, `types/struct.h`, `types/time.h`, and `types/union.h`.
This series also contains a small number of bug fixes.

Extend test coverage of hilti::rt

---

hilti/include/rt/deferred-expression.h
hilti/include/rt/types/reference.h
hilti/src/rt/tests/reference.cc

This patchset is part of #468, in particular the work on `hilti/rt/types/reference.h`.

Increase test coverage for reference types in hilti-rt library

---

.cirrus.yml
ci/Makefile

This is to work around https://github.com/cirruslabs/cirrus-ci-docs/issues/692

Cirrus CI: Move Zeek package specs back into tasks.

---

docker/Dockerfile.centos-8

`hilti::rt::init` needs to be able to set the locale on the host system
and will abort with a fatal error if it cannot do so. This patch makes
sure this is possible in the centos-8 Docker container provided by us.
Note: This already worked in BTests since its config file enforces the
needed environment variables. This patch fixes it also for standalone
usage of Spicy (and now e.g., the `locale` command emits no more
errors).

Explicitly set locale in centos Docker container.

---

hilti/src/compiler/codegen/ctors.cc

`rt::Time` internally stores timestamps as `uint64_t` values. We however
where previously using the constructor from seconds in `double` when
generating C++ code, additionally formatting double values with only 6
significant digits via `%f`. This could lead to loss of precision, e.g.,
for very small time values.
With this patch we now construct `rt::Time` values from nanoseconds.
This prevents this particular loss of precision.
This closes #508.

Prevent loss of precision when codgening Time constructors.

---

doc/host-applications.rst
doc/installation.rst
hilti/runtime/include/type-info.h
tests/hilti/codegen/type-info.hlt

It turns out that std::function not only adds runtime overhead, but also
that it is significantly slower to compiler than a function pointer.
This commit partially addresses #546.

Use plain function pointers for type info accessors.

---

docker/Dockerfile.centos-8

This was supposedly fixed with #481, but seemed broken again. With the
fix here we get the expected `C` locale set also in shell sessions.

Correctly set locale in centos8 image.

---

doc/autogen/types/enum.rst
hilti/runtime/include/type-info.h
hilti/runtime/include/types/all.h
hilti/runtime/include/types/enum.h
hilti/toolchain/include/ast/operators/enum.h
hilti/toolchain/src/compiler/codegen/operators.cc
tests/Baseline/hilti.types.enum.basic/output
tests/hilti/types/enum/basic.hlt

Returns true if the enum maps to a known type value other than Undef.
Closes #499.
(This uses our new type information for the check. We should move enum
printing to that style as well, instead of generating dedicated
functions for each enum type.)

Provide has_label() method for enum values.

---

doc/examples/_usage-spicyc.output
doc/host-applications.rst
hilti/toolchain/src/compiler/driver.cc
tests/Baseline/hilti.hiltic.print.globals/output
tests/Baseline/hilti.hiltic.print.hello-world/output
tests/hilti/hiltic/print/empty.hlt
tests/hilti/hiltic/print/globals.hlt
tests/hilti/hiltic/print/hello-world.hlt
tests/hilti/hiltic/print/import.hlt
tests/spicy/doc/my-http-host-callback.cc
tests/spicy/doc/my-http-host-driver.cc
tests/spicy/doc/my-http-host-parse1.cc
tests/spicy/doc/my-http-host-parse2.cc

This option used to print the linker glue code along with the main,
generated C++ code. The problem is that the linker code was produced
as if it were a standalone C++ unit. However, by concatening it with
the main code, that didn't hold and we'd run into problems like
duplicaste type definitions. This wasn't salvagable easily, and
conceptually it looks kind of wrong anyways, so removing it.
The better way to do all this is using "-l" to generate *just* the
linker code, then compile the two together as two compilation units.
If one insists, one can also still "cat" the two and will be back to
what "-cK" used to produce, with the same issues obviously.
Closes #500.

Remove --include-linker option from driver.

---

hilti/runtime/src/types/regexp.cc
spicy/toolchain/src/compiler/codegen/parsers/literals.cc
tests/Baseline/spicy.types.sink.write-open-end-regexp/output
tests/spicy/types/sink/write-open-end-regexp.spicy

Closes #540.
We'd mess up tracking of the current offset inside the stream.

Fix bug in regular expression parsing.

---

hilti/toolchain/include/compiler/driver.h
hilti/toolchain/src/compiler/driver.cc
spicy/toolchain/bin/spicy-driver.cc
tests/Baseline/spicy.tools.spicy-driver-missing-jit/output
tests/Scripts/have-jit
tests/spicy/tools/spicy-driver-missing-jit.spicy

Provide error message when attempting to have spicy-driver compile  when JIT is not available

---

doc/zeek.rst
tests/Baseline/zeek.evt.file-analyzer-property/output
tests/zeek/evt/file-analyzer-property.zeek
tests/zeek/evt/import-from.zeek
zeek/plugin/src/plugin.cc

Unit-side %port and %mime-type may properties may be used instead of
specifying them inside the EVT file.
Closes #95.

Zeek plugin: Respect %port and %mime-type properties in units.

---

hilti/runtime/include/types/optional.h
hilti/runtime/include/types/port.h
hilti/runtime/src/tests/optional.cc
hilti/runtime/src/tests/to_string.cc
spicy/runtime/include/parsed-unit.h
spicy/runtime/src/tests/parsed-unit.cc
tests/Baseline/spicy.rt.debug-trace/.stderr
tests/spicy/rt/debug-trace.spicy

This now lets "-X trace" work for Spocy parsers.
Closes #159.

Add some missing operator<< to runtime library.

---

spicy/toolchain/include/compiler/detail/codegen/codegen.h
spicy/toolchain/include/compiler/detail/codegen/grammar-builder.h
spicy/toolchain/src/compiler/codegen/codegen.cc
spicy/toolchain/src/compiler/codegen/grammar-builder.cc
tests/Baseline/spicy.types.unit.switch-nested/output
tests/Baseline/spicy.types.unit.trimming/.stderr
tests/spicy/types/unit/switch-nested.spicy

With nested productions, we could end up generating colissions.
Closes #531.

Make generated grammar symbols globally unique during Spicy codegen.

---

.cirrus.yml
CMakeLists.txt
ci/run-ci
configure
hilti/CMakeLists.txt
hilti/toolchain/CMakeLists.txt
hilti/toolchain/include/base/util.h
hilti/toolchain/src/base/util.cc
hilti/toolchain/src/compiler/clang.cc
hilti/toolchain/src/config.cc.in
hilti/toolchain/tests/util.cc
scripts/CMakeLists.txt
scripts/precompile-headers.sh
spicy/runtime/include/global-state.h

This patch adds precompilation for libhilti.h. This header is included
in all files during JIT, and precompiling it can for individual files
reduce JIT time by up to 30%.
In this patch we enable use of the precompiled header only during JIT,
but e.g., not when building Spicy targets. This allows us to profit from
faster JIT while still making efficient use of e.g., ccache.
Additionally, this approach allows us to punt on fixing a number of
issues in header files which get exposed during JIT (JIT artifacts are
not affected at the moment).
The original goal was to precompile lihilti.h before installation which
is not reached. In general, it seems that precompiled headers are not
intended to be moved after creation. This poses a challenge when the
header gets installed: while we could in …

Optionally precompile libhilti.h.

---

zeek/plugin/include/packet-analyzer.h

Without this little fix I'm getting the following on my machine (Fedora 33, gcc 10.2.1):
```
[ 88%] Building CXX object zeek/plugin/CMakeFiles/_Zeek-Spicy.linux-x86_64.dir/src/plugin.cc.o
In file included from /home/christian/devel/zeek/spicy/zeek/plugin/src/plugin.cc:20:
/home/christian/devel/zeek/spicy/zeek/plugin/include/zeek-spicy/packet-analyzer.h: In member function ‘void spicy::zeek::rt::PacketState::DebugMsg(const string_view&)’:
/home/christian/devel/zeek/spicy/zeek/plugin/include/zeek-spicy/packet-analyzer.h:44:50: error: ‘_debug’ was not declared in this scope; did you mean ‘debug’?
44 |     void DebugMsg(const std::string_view& msg) { _debug(msg); }
|                                                  ^~~~~~
|                                                  debug
make[3]: *** …
```

Fix "'_debug’ was not declared in this scope" build error

---

hilti/runtime/src/tests/fmt.cc

This patch bumps tinyformat to a version containing the upstream fix for
https://github.com/c42f/tinyformat/issues/76 (and the follow up fix
https://github.com/c42f/tinyformat/pull/80).
We also add a regression test.
Closes #571.

Fix padding handling when formatting nan and inf values.

---

doc/programming/language/types.rst
spicy/toolchain/src/compiler/parser/parser.yy
tests/spicy/types/tuple/operators.spicy

In Spicy, `tuple(1,2,3)` is now the same as `(1,2,3)`, and `tuple(1)` is the
same as `(1,)`. This is for consistency with other types, and to get around the
awkward syntax for single-element tuples.
Closes #389.

Add additional tuple constructor expression.

---

spicy/toolchain/src/compiler/codegen/unit-builder.cc
spicy/toolchain/src/compiler/visitors/id-resolver.cc
tests/spicy/types/vector/parse-size.spicy

Two issues:
1. The "foreach" attribute wasn't passed on.
2. The '$$' lookup didn't work inside a non-inline hook.
Closes #583.

Fix "foreach" inside a unit hook.

---

doc/autogen/types/vector.rst
hilti/runtime/include/types/vector.h
hilti/runtime/src/tests/vector.cc
hilti/toolchain/include/ast/operator.h
hilti/toolchain/include/ast/operators/vector.h
hilti/toolchain/src/compiler/codegen/operators.cc
spicy/toolchain/src/compiler/codegen/parser-builder.cc
tests/hilti/types/vector/ops.hlt

Closes #584 and #535.
(Also uses new resize() method at one place in parser builder.)

Add new vector methods resize/sub/at.

---

tests/hilti/hiltic/cc/leak.cc
tests/hilti/hiltic/jit/leak.cc

Explicitly enable leak checking on test relying on it being active.

---

doc/installation.rst
hilti/toolchain/include/config.h.in
hilti/toolchain/src/config.cc.in

JIT needs precompiled headers created by Clang while AOT compilation
probably needs them to be created by GCC (`spicy-config --cxx` would
always report the compiler used to build Spicy).
Closes #603.

Disable precompiled headers if we are building with GCC. 

---

hilti/runtime/include/types/bytes.h
hilti/runtime/src/tests/bytes.cc
hilti/runtime/src/tests/stream.cc
hilti/runtime/src/types/bytes.cc

We were using a member initializer for the `Bytes` control block which
was accessing `this`. Since member initializers are executed before
`this` is fully formed and could contain random garbage. This patch
moves the initialization of the control block into `Bytes` constructors.
We also tightened up how we create temporary `Bytes` objects since they
might now in some places correctly expired before being used.
This closes #599.

Fix construction of Bytes.

---

tests/spicy/rt/time.spicy

This test hardcodes an expected range for the current time. With this
patch we widen the acceptable range to New Year's Day 2025.

Let test 'spicy.rt.time' work for the next 4 years.

---

doc/installation.rst

In 9168ed7cd0ef8988405abac9512d863f4df09486 we moved some Docker images
from non-LTS ubuntu-19 to ubuntu-18. This patch makes a sweep of the
docs to remove now outdated references to ubuntu-19 and replaces them
with ubuntu-18 instead.

Fix doc references to docker-19.

---

.github/workflows/create-release.yml
.gitignore
scripts/autogen-version
scripts/make-tarball.sh

This PR adds a script to create a release tarball and a GH action
attaching which creates and attaches the tarball to any release tags
pushed to the repo. We assume that that release tags are of the form
`v*`.
Closes #650.

Add script to create release tarball.

---

.cirrus.yml
ci/prepare_freebsd.sh
hilti/toolchain/bin/hilti-config.cc
hilti/toolchain/src/config.cc.in
spicy/toolchain/bin/spicy-config.cc
tests/spicy/doc/my-http-host-driver-hlto.cc

We previously were adding logic for either Apple or Linux platforms
which left this broken on FreeBSD. This patch simplifies the logic so
that we now only perform special handling on Apple and use the same
behavior elsewhere.
Closes #634.

Fix dynamic loading flags on FreeBSD.

---

ci/prepare_freebsd.sh

Cirrus CI have bumped their FreeBSD instance images so this step is not
necessary anymore (and would in fact fail as the files are already
present).

Remove manual installation of Zeek CMake files on FreeBSD CI.

---

hilti/runtime/include/configuration.h

macOS needs more it seems when compiling with the native compiler.
Closes #664.

Increase minimum fiber stack size.

---

.cirrus.yml
docker/Dockerfile.alpine-3.12
docker/Dockerfile.centos-7
docker/Dockerfile.centos-8
docker/Dockerfile.debian-10
docker/Dockerfile.debian-9
docker/Dockerfile.fedora-32
docker/Dockerfile.fedora-33
docker/Dockerfile.ubuntu-16
docker/Dockerfile.ubuntu-18
docker/Dockerfile.ubuntu-20

Since we now compile directly with the system compiler we do not
strictly require LLVM anymore. This patch simplifies the in-tree Docker
images so they use the default compiler for the platform if possible;
since we require a C++17-capable compiler we still need to install
custom compilers on a number of platforms.

Use "default" compiler if possible in Docker images.

---

.cirrus.yml

Cirrus tasks with `only_if` are hidden unless there condition is met.
With that it becomes impossible to trigger them from PRs. Use `skip`
with an inverted condition instead so we can optionally trigger them
even from PRs (this can become handy to check more expensive tasks
before merging).

Make master-only CI tasks triggerable.

---

.cirrus.yml
doc/installation.rst

We still have a platform (debian-10) which is currently disabled in CI.
We add a TODO for that in the CI configuration.
We also document direct links to macOS artifacts; these links however
appear to be broken at the moment.

Document more platforms in the installation docs.

---

doc/autogen/types/bytes.rst
doc/autogen/types/list.rst
doc/autogen/types/map.rst
doc/autogen/types/set.rst
doc/autogen/types/stream.rst
doc/autogen/types/vector.rst
hilti/toolchain/include/ast/operators/generic.h
spicy/toolchain/bin/spicy-doc.cc

This needs to hardcode the list of iterable container type unfortunately
as we don't have a way to enumerate them automatically.
Closes #640.

Extend spicy-doc to document begin/end operators.

---

doc/autogen/zeek-functions.spicy
tests/zeek/evt/file-analyzer.zeek
tests/zeek/evt/ssh-banner.zeek
zeek/plugin/include/runtime-support.h
zeek/plugin/spicy/zeek.spicy
zeek/plugin/src/runtime-support.cc

zeek::uid() and zeek::fuid() return the current connection UID and file
FUID, respectively.
Closes #688.

Zeek plugin: Add functions to access UIDs and FUIDs.

---

.cirrus.yml
.github/workflows/docker-latest.yml
.github/workflows/docker-tags.yml
docker/Dockerfile.alpine-3.12
docker/Dockerfile.centos-7
docker/Dockerfile.centos-8
docker/Dockerfile.fedora-32
docker/Dockerfile.fedora-33
docker/Dockerfile.ubuntu-16
docker/Dockerfile.ubuntu-18
docker/Dockerfile.ubuntu-20

This changeset updates the included Docker images so that the included
Zeek installation is usable with Spicy without further configuration.

Make Docker images standalone.

---

doc/conf.py

Calculating version information requires an undeterministic extended
amount of Git history. Since the readthedocs build process by default
clones only up to of 50, this means that often we will not be able to
compute the expected history format (e.g., `d2e94ba8 (master d2e94ba8)`
instead of `0.4.0-1330 (master d2e94ba8)`).
With this patch we now fetch the full history in readthedocs.
Closes #707.

Fetch full history when building documentation in readthedocs.

---

scripts/store-release-artifacts

This patch adds a script to download packaging artifacts of a Cirrus
build and optionally upload them to a release.
Closes #699.

Add script to store and upload release artifacts.

---

ci/Dockerfile
doc/Makefile
doc/conf.py
doc/examples/frontpage.spicy
doc/getting-started.rst
doc/host-applications.rst
doc/index.rst
doc/installation.rst
doc/programming/language/modules.rst
doc/programming/language/variables.rst
doc/programming/parsing.rst
doc/scripts/spicy-pygments.py
doc/scripts/spicy.py
doc/tutorial/index.rst
doc/zeek.rst

* Add a `livehtml` target which uses `sphinx-autobuild` for convenience
* Add Pygments syntax highlighters for `.spicy` and `.evt` files
* Use syntax highlighting for spicy/spicy-evt/zeek/c++ languages in the docs

Add syntax highlighting to docs

---

zeek/plugin/include/runtime-support.h
zeek/plugin/include/zeek-compat.h
zeek/plugin/src/config.h.in

* Include paths require using <zeek/zeek-config.h>
* Val constructors that take raw pointers are gone, replaced by ones
taking IntrusivePtr
* The global event_registry is replaced by zeek::event_registry
(There's also https://github.com/zeek/zeek/pull/1390 required to get Spicy compiling w/ current zeek/master branch)

Fix compatibility with Zeek 4.1 API changes/removals

---

doc/installation.rst

At one point the links to Cirrus CI artifacts for macOS tasks was
broken, but it seems to be working again.
Closes #682.

Remove TODO in docs [skip ci].

---

spicy/toolchain/src/compiler/codegen/parser-builder.cc

Skip evaluating `parse-at` or `parse-from` if field condition is False.

---

doc/programming/parsing.rst

Explicitly mention that boolean expressions are allowed.
(i.e. what would help in relation to #771)

Improve docs for vector &until parsing

---

.cirrus.yml
hilti/runtime/src/tests/bytes.cc
hilti/runtime/src/tests/library.cc
hilti/toolchain/include/base/util.h
hilti/toolchain/src/ast/module.cc
hilti/toolchain/src/compiler/visitors/apply-coercions.cc
spicy/runtime/src/tests/parser.cc
spicy/toolchain/src/compiler/codegen/parser-builder.cc
zeek/compiler/driver.cc

We already have this on for CI setups using `run-ci`, but need to
specify it explicitly for platforms using the document build method via
`./configure`.

Build with -Werror in CI.

---

hilti/runtime/src/util.cc

The HILTI unit tests fail on my system:
```
$ cd build
$ ctest
Test project /home/christian/devel/zeek/spicy/build
Start 1: hilti-rt-tests
1/5 Test #1: hilti-rt-tests ...................***Failed    0.13 sec
Start 2: hilti-rt-configuration-tests
2/5 Test #2: hilti-rt-configuration-tests .....   Passed    0.01 sec
Start 3: hilti-toolchain-tests
3/5 Test #3: hilti-toolchain-tests ............   Passed    0.03 sec
Start 4: spicy-rt-tests
4/5 Test #4: spicy-rt-tests ...................   Passed    0.01 sec
Start 5: spicy-toolchain-tests
5/5 Test #5: spicy-toolchain-tests ............   Passed    0.02 sec
80% tests passed, 1 tests failed out of 5
Total Test time (real) =   0.20 sec
The following tests FAILED:
1 - hilti-rt-tests (Failed)
Errors while running CTest
```
This is due to:
```
$ …
```

Fix strftime unit test: increase portability of localtime_r() usage

---

zeek/plugin/include/runtime-support.h

While we previously provided specialized conversion functions to Zeek
`ValPtr` these were not used for plain integer types like e.g.,
`std::size_t` or `unsigned long`. Instead C++ overload resolution
preferred to instead convert the integers to `double` (for which we
provide a specialization) and them being emitted with `TYPE_DOUBLE`.
This patch introduces an additiona specialization which converts such
naked integers to safe integers and then converts them.
Closes #798.

Prevent conversions of some integers to doubles on the Zeek interface.

---

doc/programming/examples.rst

The analyzers had moved to zeek/spicy-analyzers previously.
Closes #804.

Fix links to example Spicy analyzers.

---

scripts/run-benchmarks

We recently moved the analyzers from this repo to zeek/spicy-analyzers.
This broke the benchmark setup which still hardcoded the old, now
non-existing paths.
This patch adjusts the paths to now reference the new locations.
We also fix a number of other issues in the benchmark runner:
- the script now aborts on error were it previously continued with
possibly broken state,
- all standalone binary and standalone HLTO benchmarks where
benchmarking the HTTP parser; we now generate the correct benchmarks
from the correct input scripts (this means that previous benchmark
results for anything other than HTTP are not useful and cannot be
compared to).
Closes #806.

Fix benchmark script for move of analyzers.

---

hilti/toolchain/include/base/util.h
hilti/toolchain/src/compiler/driver.cc
hilti/toolchain/tests/util.cc

Fix unification of internal compiler arguments to not change order.

---

spicy/lib/spicy_rt.hlt
spicy/runtime/include/parser.h
spicy/runtime/src/parser.cc
spicy/runtime/src/tests/parser.cc
spicy/toolchain/src/compiler/codegen/parser-builder.cc

When parsing a vector bounded by &eod, the parser could enter the
code for reading the next element too early before it could reliably
tell that EOD hadn't been reached yet. The fix is to change `atEod()` so
that if stream is still unfrozen, it waits for at least one available
byte before making the decision.
This is hard to test for because it requires yielding & resuming the
input in the right way, but the PNG can act as a test case: it was
producing an unexpected weird, which is now gone.
Closes #817.
Merge with https://github.com/zeek/spicy-analyzers/pull/19

Fix vector parsing potentially missing EOD.

---

hilti/toolchain/include/ast/operators/struct.h

It would require a non-const struct, for no reason.

Fix `?.` operator to work with constant structs.

---

.cirrus.yml
.clang-format
ci/Dockerfile
ci/Dockerfile.dockerhub
ci/Dockerfile.packages
docker/Dockerfile.centos-7
docker/Dockerfile.centos-8
docker/Dockerfile.debian-10
docker/Dockerfile.debian-9
docker/Dockerfile.fedora-32
docker/Dockerfile.fedora-33
docker/Dockerfile.ubuntu-16
docker/Dockerfile.ubuntu-18
docker/Dockerfile.ubuntu-20
hilti/toolchain/include/ast/types/struct.h
hilti/toolchain/src/compiler/cxx/elements.cc

We still keep at least a single setup with zeek-3.0.0 so we also have
some coverage there.
Closes #827.

Bump Zeek LTS version to 4.0.0 in some CI and Docker images.

---

hilti/runtime/include/types/integer.h
hilti/runtime/src/tests/integer.cc

When calculating the extraction mask, we previously would shift an
integer beyond its width which triggers UB. With this patch we now
correctly detect such cases and directly return the input.
Closes #853.

Fix extraction of integer bits when all bits requested.

---

.github/workflows/docker-latest.yml

The comment was not valid in its previous place which allowed only
tags. This patch moves it to a proper place.
This is a fixup commit for 843e9e0073006b5c8eee5568e5a9d69fcd834250.

Fix YAML comment in docker-latest GH workflow [skip ci].

---

doc/conf.py

We recently renamed packages from e.g., `spicy.deb` to `spicy-dev.deb`
which wasn't reflected in the docs.
Additionally, due to the CI setup `.tar.gz` artifacts live in
`packages/build` while `.deb` and `.rpm` artifacts live in `packages/`;
we fix the links for that as well.

Fix doc links to package artifacts.

---

.github/workflows/docker-latest.yml
.github/workflows/docker-tags.yml

We were still hardcoding `master` as our default branch in the GH action
responsible for publishing Docker images. This patch fixes that name
mismatch; we also disable to workflow for publishing tags on `main`
(this was still enabled since we didn't publish properly versioned
images before).

Fix leftovers in GH actions from master -> main rename.

---

hilti/toolchain/include/ast/operator.h

Some compilers diagnose the function changed here as having a missing
return. Since we switch over all possible values we should never return
without a value, though.
This patch adds a runtime assertion that we do not return without a
value.

Add assertion to ensure that code cannot be reached.

---

hilti/toolchain/src/compiler/codegen/expressions.cc

They weren't turned into proper C++ codegen IDs, meaning they weren't
normalized.
(Skipping test.)
Closes #872.

Fix missing normalization of enum label IDs.

---

CHANGES
scripts/autogen-version

update-changes and autogen-version didn't agree on how to number
development versions.

Fix versioning for development.

---

hilti/toolchain/src/compiler/cxx/unit.cc

We could run into some dependencies where the types being referred to in
the type information weren't declared yet.
No test included, as it's hard to recreate the situation; will be
tested through an upcoming change to the Zeek plugin.

Force type information to come last in generated C++ code.

---

doc/autogen/spicy-functions.spicy
hilti/lib/hilti.hlt
hilti/runtime/include/types/time.h
hilti/runtime/src/tests/time.cc
hilti/runtime/src/types/time.cc
spicy/lib/spicy.spicy
tests/hilti/types/time/functions.hlt

This allows creating a `time` value from individual compenents, similar
to mktime(3). Providing to both HILTI and Spicy code.

Provide mktime() library function.

---

CMakeLists.txt
ci/Dockerfile.packages
cmake/Util.cmake
docker/Dockerfile.centos-7
docker/Dockerfile.centos-8
docker/Dockerfile.debian-10
docker/Dockerfile.debian-9
docker/Dockerfile.ubuntu-16
docker/Dockerfile.ubuntu-18
hilti/toolchain/CMakeLists.txt
hilti/toolchain/src/compiler/parser/parser.yy
spicy/toolchain/CMakeLists.txt
spicy/toolchain/src/compiler/parser/parser.yy

This also allows compiling under OpenSUSE Leap 15.2, which only ships with bison 3.0.4.
Relates to GH-882

Make spicy compile with bison 3.0.

---

CMakeLists.txt
hilti/runtime/CMakeLists.txt
scripts/autogen-version

As part of the Windows port effort.
Output checked against the old bash version with several configurations.
- ~~Bump the minimum python3 version to 3.7. 
While asking for python3.7 in 2021 is probably reasonable I realize that this version bump might be a bit extreme, considering that the other python scripts in the repo apparently run on 3.2. With some readability sacrifices we can target something lower than 3.7 if that's a requirement.~~
After a minor change the now required minimum is 3.6, which is what centos7 ships,
- Explicitly invoke `Python3_EXECUTABLE` in the cmake commands that need them (workaround for shebangs not working on Windows). For now this is limited to autogen-version calls.

Port autogen-version to python3

---

hilti/runtime/include/types/map.h
hilti/runtime/include/types/set.h
hilti/runtime/include/types/vector.h

For the HILTI runtime containers we previously directly forwarded the
`size` functions of the underlying stdlib containers. This could have
lead to them returning a type not expected by our runtime, e.g., on
macos these might return `unsigned long` values which our runtime e.g.,
doesn't know how to print.
This patch changes these functions so that now they return types which
we expect our runtimes to be able to work with.

Make sure container sizes are runtime integers.

---

.github/workflows/create-release.yml

While this still requires us to create public tags, marking the releases
initially as drafts removes confusion for users who might end up using a
release we ultimately might not intend to publish.

Make only draft releases from automation [skip ci].

---

.github/workflows/docker-latest.yml
.github/workflows/docker-tags.yml
ci/Dockerfile.dockerhub

Github action runners only have limited resources (currently for Linux:
2 CPUs, 7GB RAM). In the build of the spicy-plugin and spicy-analyzers
Zeek packages we previously hardcoded a certain level of parallelism,
which caused us to run into especially RAM limits when building
spicy-analyzers. With recent versions of these packages we can now
optionally externally parameterize the level of parallelism to use.
This patch adjust the Github action setup so we build these packages
with a number of processes compatible with the runners we will be faced
with.

Adjust processes used to build Docker image.

---

hilti/toolchain/src/compiler/cxx/elements.cc
tests/hilti/codegen/element_init.hlt

When codegen'ing a struct constructor which can initialize all fields
from passed in values we previously distinguished names of our arguments
from the user-specified fields by appending a `_` to our arguments. This
could have lead to name collisions if user code contain field names
differing only in whether they contained a final `_`.
With this patch we take a different approach in that we now explicitly
qualify access of fields with `this->`.

Avoid name collision when codegen'ing struct element initializers.

---

.cirrus.yml
docker/Dockerfile.debian-11

This PR adds support for Debian Bullseye to CI.
Since Bullseye comes with GCC 10, we do not need to install the LLVM toolchain manually.
According to the [install docs](https://docs.zeek.org/projects/spicy/en/latest/installation.html), we need at least CMake 3.15. Bullseye ships with 3.18, so we can use `apt` to install all dependencies.

Add Debian Bullseye to CI

---

hilti/toolchain/src/compiler/codegen/codegen.cc
tests/spicy/types/unit/vector-field-link-glue.spicy

Emit linker glue type definitions for vector fields.

---

.cirrus.yml
CMakeLists.txt
hilti/runtime/src/tests/util.cc

Swallow Git error messages during CMake if run from tarball.

---

doc/installation.rst

Use publicly accessible links to Docker images.

---

.github/workflows/docker-latest.yml
.github/workflows/docker-tags.yml

The DockerHub org we publish to previously matched the user we used to
log in to DockerHub, so we could avoid hardcoding the full org name.
Since we now use a bot account to publish to DockerHub this is not
true anymore and we need to specify the org explicitly.
This patch hardcodes the org name as `zeekurity` into Github workflows
publishing images to DockerHub.

Hardcode DockerHub org we publish images for in GH workflow.

---

hilti/runtime/include/types/map.h
hilti/runtime/include/types/set.h
hilti/runtime/include/types/vector.h
hilti/runtime/src/tests/map.cc
hilti/runtime/src/tests/set.cc

When generating code we directly expose the size function of runtime
containers in generated code. We previously would use naked `uint64_t`
or `size_t` which aren't really types e.g., generated code handles well;
instead it in general expects integer types to be some `integer::safe`.
This patch changes the runtime container size functions to return safe
integer values.
Closes #988.

Use safe integer for runtime container sizes.

---

hilti/runtime/src/fiber.cc

Since we currently do not test on arm64 we do not advertize it as a
supported platform.

Make it possible to build on arm64.

---

CMakeLists.txt
hilti/CMakeLists.txt
scripts/precompile-headers.sh
spicy/runtime/include/libspicy.h
spicy/toolchain/src/config.cc.in

Since only a single precompiled header can be explicitly added we need
to add this header to Spicy's `CXXFLAGS` differently in that it replaces
any precompiled header for `libhilti.h` we inherited from the HILTI
config.
We also include `libhilti.h` in `libspicy.h` now so we still get the
precompilation benefits for that part as well.

Precompile `libspicy.h`.

---

hilti/toolchain/include/compiler/detail/parser/driver.h
hilti/toolchain/src/compiler/parser/parser.yy
spicy/toolchain/include/compiler/detail/parser/driver.h
spicy/toolchain/src/compiler/parser/parser.yy

With bison-3.8.1 redefining `YYSTYPE` instead of `%define
api.value.type` has been deprecated and now triggers a warning.

Fix parsers for bison-3.8.1.

---

hilti/runtime/src/fiber.cc

In 89d3295f1363d8d07eda5c711740b18f31483d88 we adjusted some
preprocessor code to enable building on arm64. That patch missed an
update of another instance to the same conditional which we fix with
this patch.
Some ARM64 platforms do not seem to reliably set the `__arm64__` define,
but instead `__aarch64__`. We now allow that as an alternative.

More fixes for building on ARM64.

---

hilti/runtime/include/types/bytes.h
hilti/runtime/include/types/vector.h
hilti/runtime/src/tests/bytes.cc
hilti/runtime/src/tests/regexp.cc
hilti/runtime/src/types/regexp.cc
hilti/runtime/src/types/stream.cc
spicy/runtime/include/sink.h

In fd5c53cb8ffd1a18aadb7d21b927bda801e264c8 we changed the size
functions of runtime containers to use safe integers. This patch adjusts
the remaining size functions to use safe integers as well.
We also add a test for `RegExp::find` with empty needle. While the
behavior of that function should not have changed with this patch, we
still had to adjust its implementation.

Use safe integers for runtime size functions.

---

hilti/toolchain/src/compiler/optimizer.cc
tests/Baseline/spicy.optimization.default-parser-functions/log
tests/Baseline/spicy.optimization.feature_requirements/log
tests/Baseline/spicy.optimization.unused-functions/log
tests/Baseline/spicy.optimization.unused-types/log
tests/spicy/types/unit/switch-convert-mixed.spicy

This patch simplifies code by using AST canonical IDs, and by accessing
a unit's method via `parent`. Since `Field`s are now declarations we can
also simplify code related to that.

Clean up optimizer after AST rework.

---

hilti/toolchain/include/compiler/unit.h
hilti/toolchain/src/compiler/codegen/codegen.cc
hilti/toolchain/src/compiler/codegen/types.cc
hilti/toolchain/src/compiler/driver.cc
hilti/toolchain/src/compiler/unit.cc
tests/Baseline/hilti.hiltic.print.globals/output
tests/Baseline/hilti.hiltic.print.hello-world/output
tests/Baseline/hilti.hiltic.print.import/output
tests/Baseline/hilti.hiltic.print.yield/output
tests/Baseline/spicy.tools.spicyc-hello-world/test.hlt

We recently started including type information for all types that a
module included. That doesn't harm functionally, but increased code
size and compilation time. This patch reverts that to the old behavior.
Doing so required one additional fix for exceptions, which had
generation of their destructor tied to the generation of type
information; which now doesn't work anymore, but also seems unnecessary
in the first place.
Addresses #1009.

Fix overly generous generation of type information.

---

hilti/toolchain/include/compiler/detail/visitors.h
hilti/toolchain/include/compiler/plugin.h
hilti/toolchain/include/compiler/unit.h
hilti/toolchain/src/compiler/driver.cc
hilti/toolchain/src/compiler/plugin.cc
hilti/toolchain/src/compiler/unit.cc
hilti/toolchain/src/compiler/visitors/validator.cc
spicy/toolchain/include/compiler/detail/visitors.h
spicy/toolchain/src/compiler/plugin.cc
spicy/toolchain/src/compiler/visitors/validator.cc
tests/Baseline/hilti.ast.basic-module/output
tests/Baseline/hilti.ast.imported-id/output
tests/Baseline/hilti.ast.types/output

One validation pass runs before AST resolving, one afterwards. The first
can be used for any checks that don't need any further worn on that AST
so that they can abort processing quickly.
Right now, the pre-resolver validators are empty no-ops, nothing has
moved over yet.
Addresses #1013.

Split validation into two passes.

---

doc/requirements.txt

This resolves the build problems due to sphinx-doc/sphinx#9727 we've
been seeing.

Fix build for RTD.

---

hilti/runtime/include/types/stream.h

To construct `UnsafeConstIterator`s we previously directly used a
`SafeConstIterator`'s chunk pointer which might be invalid and point to
e.g., random memory. With this patch we use the safe API to retrieve it
which either yields a valid pointer to a chunk or a `nullptr` (which we
also handle).

Fix potentially use-after-free in stringification of `stream::View`.

---

ci/Dockerfile.dockerhub

In order to use packages with dependencies we require
zeek/package-manager#106 which is only available with zkg-2.12.0.

Bump zkg in published Docker image.

---

.github/workflows/docker.yml

This patch fixes a typo in filter the login steps in the workflow
publishing container images (`github.event.name` instead of
`github.event_name`). Since the mistyped variable was undefined we
previously never performed the login.

Fix a typo in container Github action filter.

---

CMakeLists.txt
spicy/toolchain/CMakeLists.txt

We currently always execute some commands, even if we just completed a
build. This PR addresses that.

Fixes for noop build

---

hilti/toolchain/include/compiler/unit.h
hilti/toolchain/src/compiler/unit.cc
tests/Baseline/hilti.ast.imported-id/output
tests/spicy/types/unit/transitive-imports.spicy

Fix code generator to emit types correctly for transitive dependencies.

---

hilti/toolchain/src/compiler/context.cc
hilti/toolchain/src/compiler/driver.cc

This PR removes unneeded computations around logging. While this only
speeds up the test suite by around 20% on my machine (hot ccache), it
nearly halves the time it takes to process a huge grammar (~1500 loc,
~130 units, timing excluding C++ compilation).

Remove unneeded computations

---

configure

In 945dd34a5e49a we attempted to fix the issue of `./configure` failures
not leading to error return codes by explictly capturing the log and showing it
later. This introduced the issue that the configure log was only
shown after `./configure` finished _successfully_; on configure failure
we would correctly return an error code, but never reach the code
displaying the log.
This patch fixes this puzzling behavior so that the log is even shown
if `configure` runs into issues. For that we use the `pipefail` Bash
option.

Show log for configure failures.

---

doc/programming/language/variables.rst

Globals can have default or `public` visibility. This patch adds
documentation for declaring them `public`.

Document visibility for globals [skip CI].

---

doc/programming/language/types.rst
spicy/toolchain/src/compiler/parser/parser.yy
tests/spicy/types/enum/type.spicy
tests/spicy/types/map/ops.spicy
tests/spicy/types/struct/basic.spicy
tests/spicy/types/struct/parse-fail.spicy

We previously supported declaring `struct` types in Spicy with HILTI
syntax, i.e., fields were declared like
TYPE IDENTIFIER [ATTRIBUTES];
This syntax does not fit Spicy well so this patch adjusts the syntax for
`struct` field declarations to be
IDENTIFIER: TYPE [ATTRIBUTES];
We also update the recently added documentation for `struct` types.
Closes #1068.

Fix syntax for Spicy `struct` declaration.

---

hilti/toolchain/src/compiler/codegen/codegen.cc
tests/hilti/codegen/imported-constants.hlt

We were treating them as globals (instead of constants) and weren't
emitting them into the generated C++ code.
Closes #1079.

Fix import of global constants.

---

hilti/runtime/include/fiber.h
hilti/runtime/include/types/address.h
hilti/runtime/include/types/bytes.h
hilti/runtime/include/types/integer.h
hilti/runtime/include/types/port.h
hilti/runtime/include/types/real.h
hilti/runtime/include/types/stream.h
hilti/runtime/include/util.h

In order to convert from arbitrary runtime values with
`hilti::rt::enum_::{from_int, from_uint}` we statically assert that the
enums have an underlying type `int64_t`. This is not true in general,
e.g., a port enum would previously have been represented by an `int`
(which not only does not need to be the same time, but could also have a
smaller range).
With this path we now explicitly request an underlying type `int64_t`
for enums which can be constructed by users from Spicy code.
Closes #1122.

Make sure user-visible enums are represented by `int64_t`.

---

hilti/toolchain/src/compiler/codegen/expressions.cc

Do not change a LHS to RHS when codegen'ing BuiltinFunctions.

---

.cirrus.yml

The `clang12_ubuntu_debug` task was getting too big and regularly ran
into timeouts while running clang-tidy. Move that part to its own job to
avoid running into the global 2h timeout in Cirrus CI.

Move clang-tidy run to its own CI job.

---

hilti/toolchain/CMakeLists.txt
hilti/toolchain/bin/hiltic.cc
hilti/toolchain/include/compiler/init.h
hilti/toolchain/include/compiler/plugin.h
hilti/toolchain/src/compiler/init.cc
hilti/toolchain/src/compiler/parser/driver.cc
hilti/toolchain/src/compiler/plugin.cc
spicy/toolchain/CMakeLists.txt
spicy/toolchain/bin/spicy-doc.cc
spicy/toolchain/bin/spicy-driver.cc
spicy/toolchain/bin/spicy-dump/main.cc
spicy/toolchain/bin/spicyc.cc
spicy/toolchain/include/compiler/init.h
spicy/toolchain/include/compiler/plugin.h
spicy/toolchain/src/compiler/init.cc
spicy/toolchain/src/compiler/plugin.cc

Support for working with Spicy and HILTI source files is handled by
plugins. We previously registered these plugins via hidden static
variables. This had issues if Spicy is linked statically and the hidden
registration variable was not linked into the final output (in that case
not registration would happen).
In order to better control the language registration this patch
introduces dedicated functions `hilti::init` and `spicy::init` which
currently only register support for HILTI and Spicy source files,
respectively. We also adjust our executables to invoke these functions
now.
Closes #1164.

Make compiler plugin initialization explicit.

---

tests/spicy/types/unit/synchronize-match-length.spicy

Both during usual parsing and synchronization we prefer the longest
possible match, see #1114. The test
`spicy.types.unit.synchronize-match-length` documented the at the time
intended behavior of taking the shortest possible match instead. This
patch brings the comments in line with the actual behavior to avoid
confusion.

Update test comments to reflect actual behavior [skip CI].

---

CMakeLists.txt
configure

This patch adds a binary packaging mode which mirrors the behavior of
that flag. In this mode Spicy gets linked statically and no RPATHs are
embedded in binaries. This should make it easier to package Spicy (e.g.,
alongside Zeek) for typical distributions which tend to disallow
embedded RPATHs.
Note that we still emit linker flags with an RPATH via e.g.,
`spicy-config --ldflags-hlto`. This RPATH is however not embedded into
distributed binary artifacts.

Add binary packaging mode.

---

.cirrus.yml

Freebsd11 is EOL and it seems upstream package servers became
unavailable. This makes it impossible to install required packages. This
patch adds support for freebsd13 instead. Since it seems that support the
the way we perform symbol demangling is currently broken in freebsd13
(see e.g., https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222563)
the step is not required.
This patch is the first, but not last piece of work to get #1171 fixed.

Remove freebsd11, add freebsd13.

---

doc/zeek.rst

I was reading through https://docs.zeek.org/projects/spicy/en/latest/zeek.html and noticed a few buglets.
One spot mentioned `spicy-config --zeek-version-number`. I think that got removed a while back, so I replaced it with `zeek -e 'print Version::number'`.

Minor edits to the Zeek Integration section

---

hilti/toolchain/src/compiler/codegen/coercions.cc

We previously would uses at least `(u)int16`, even though the the user
explicitly requested `(u)int8`. This could e.g., lead to surprising
behavior when interacting with function overloading. This patch removes
the special handling and we now use the requested type
Closes #1174.

Do not artificially suppress uses of `(u)int8` in some cases.

---

hilti/runtime/include/util.h
hilti/toolchain/include/ast/node.h
hilti/toolchain/include/base/util.h

With C++17 `std::result_of` was deprecated in favor of
`std::invoke_result`. This patch removes uses of the deprecated
template.
Closes #1190.

Replace uses of deprecated `result_of` with `invoke_result`.

---

doc/getting-started.rst
doc/tutorial/index.rst
doc/zeek.rst

This updates our docs for the rename of the plugin with
zeek/spicy-plugin#44.

Update docs for spicy-plugin rename `_Zeek::Spicy` -> `Zeek::Spicy`.

---

hilti/runtime/CMakeLists.txt
hilti/toolchain/CMakeLists.txt
spicy/runtime/CMakeLists.txt
spicy/toolchain/CMakeLists.txt

We previously did not take `DESTDIR` installs into account when removing
symlinks in the installation directory, so we never actually removed
symlinks for `DESTDIR` installs.
Closes #1201.

Adjust removal of symlinks on install for `DESTDIR`.

---

hilti/runtime/CMakeLists.txt
hilti/toolchain/CMakeLists.txt
spicy/runtime/CMakeLists.txt
spicy/toolchain/CMakeLists.txt

We previously would back to value of `DESTDIR` in at configure time.
This made it impossible to change its value at install time so that
e.g., typical uses like
make DESTDIR=<dest> install
did not perform like expected, i.e., symlinks which were supposed to be
removed at install time did not get removed due to incorrect paths. With
this patch we now evaluate the value of `DESTDIR` at install time
instead.

Allow changing `DESTDIR` between configure and install time.

---

3rdparty/CMakeLists.txt

The GNU toolchain seems to default to marking the stack of any archive
as executable if it contains assembly sources. This is the case in Spicy
since we link against 3rdparty/fiber which contains assembly source
files. If Spicy is linked statically this propagates into the binary,
for shared linkage only into libhilti; in each case this can be
confirmed with e.g., `readelf -Wl <artifact>`.
With this patch we explicitly request that the stack not to be marked
executable whenever we link fiber assembly files. Since the library does
not provide a CMake customization point for the flags we set the flag
globally for any 3rdparty sources.
Closes #1210.

Prevent unnecessarily executable stack with GNU toolchain.

---

hilti/toolchain/include/ast/operator.api
hilti/toolchain/include/ast/operators/address.h
hilti/toolchain/include/ast/operators/bytes.h
hilti/toolchain/include/ast/operators/common.h
hilti/toolchain/include/ast/operators/enum.h
hilti/toolchain/include/ast/operators/error.h
hilti/toolchain/include/ast/operators/exception.h
hilti/toolchain/include/ast/operators/function.h
hilti/toolchain/include/ast/operators/generic.h
hilti/toolchain/include/ast/operators/interval.h
hilti/toolchain/include/ast/operators/map.h
hilti/toolchain/include/ast/operators/network.h
hilti/toolchain/include/ast/operators/port.h
hilti/toolchain/include/ast/operators/regexp.h
hilti/toolchain/include/ast/operators/result.h
hilti/toolchain/include/ast/operators/set.h
hilti/toolchain/include/ast/operators/stream.h
hilti/toolchain/include/ast/operators/string.h
hilti/toolchain/include/ast/operators/struct.h
hilti/toolchain/include/ast/operators/time.h
hilti/toolchain/include/ast/operators/tuple.h
hilti/toolchain/include/ast/operators/union.h
hilti/toolchain/include/ast/operators/vector.h
hilti/toolchain/include/ast/type.h
hilti/toolchain/src/compiler/coercion.cc
hilti/toolchain/src/compiler/optimizer.cc
hilti/toolchain/src/compiler/visitors/resolver.cc
spicy/toolchain/include/ast/operators/bitfield.h
spicy/toolchain/include/ast/operators/sink.h
spicy/toolchain/include/ast/operators/unit.h

This PR collects a number of performance tweaks to speed up JIT. With a larger test grammar I saw these changes speed up JIT by around 30%.

Incremental performance tweaks for JIT

---

hilti/toolchain/src/compiler/codegen/coercions.cc
tests/hilti/types/reference/strong-ref.hlt
tests/hilti/types/reference/weak-from-strong-ref.hlt
tests/hilti/types/result/conversion.hlt

For `cast<bool>(...) we would previously produce C++ `bool` values which
could have lead to C++ ambiguities when used together with boolean
literals, e.g.,
True ? cast<bool>(1): False;
would produce either a `bool` or a `hilti::rt::Bool` where either type
can implicitly convert to the other type.
We now always produce `hilti::rt::Bool` from casts which removes the
ambiguity. For the majority of types we still go through their
`explicit` bool conversion operator which is needed in other places as
well.
Closes #1217.

Produce `hilti::rt::Bool` when casting to boolean.

---

hilti/toolchain/src/compiler/context.cc

This removes a check that a previous change had introduced, which was
actually semantically wrong. I don't quite recall why I had added
that, I think it had seemed necessary for some reason, but the test
suite runs fine without it at least.
(No test because the reproducer requires spicyz.)
Closes #1224.

Fix import segfault.

---

doc/programming/language/conditional.rst

We previously didn't make clear how minor and patch versions are encoded
in `SPICY_VERSION`. This patch modifies the given example so all three
values are different from `0`.
Closes #1240.

Clarify docs on `SPICY_VERSION` [skip CI].

---

hilti/toolchain/include/compiler/unit.h
hilti/toolchain/src/compiler/unit.cc
tests/spicy/types/unit/import-from-type-names.spicy

different means.
This can happen when mixing normal import with  `import ... from`. A
previous change to support multiple units of the same name, missed
that we could run into namespacing trouble at code generation time in
this case. The problem was that we included the `from ...` scope into
the namespace, which doesn't work when we import the same module both
w/ and wo/ scope. Now we generate unique module IDs differently
through global state independent of file system paths.
Close #1227.

Fix code generation when a module's file could be imported through

---

hilti/runtime/CMakeLists.txt
spicy/runtime/CMakeLists.txt

Fix the following build failure if `CMAKE_CXX_FLAGS_{DEBUG,RELEASE}` is empty:
```
CMake Error at auxil/spicy/spicy/hilti/runtime/CMakeLists.txt:70 (string):
string sub-command REPLACE requires at least four arguments.
CMake Error at auxil/spicy/spicy/spicy/runtime/CMakeLists.txt:49 (string):
string sub-command REPLACE requires at least four arguments.
```
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

fix build with empty CMAKE_CXX_FLAGS_{DEBUG,RELEASE}

---

hilti/toolchain/include/ast/expressions/ternary.h
hilti/toolchain/src/compiler/coercion.cc
hilti/toolchain/src/compiler/visitors/coercer.cc
hilti/toolchain/src/compiler/visitors/validator.cc
tests/spicy/types/optional/coercion.spicy

There are some situations where that's fine to coerce, so adding that.
Also adding a coercion for ternary expressions that coerces the 2dn
expression into the type of the 1st (which we already assume provides
the result type).
Closes #1143.
Closes #1220.

Add coercion for optionals that only differ in constness of their inner types.

---

hilti/runtime/CMakeLists.txt

We previously would install e.g., SafeInt test files as well. With this patch we now only install the one actually required header.
Closes #1267.

Install only needed SafeInt header.

---

doc/tutorial/index.rst
doc/zeek.rst

This updates the documentation to the changes from zeek/package-template#2, and should be merged at the same time.

Adapt Zeek instructions for zkg template updates.

---

doc/autogen/spicy-functions.spicy
doc/scripts/autogen-spicy-lib
hilti/runtime/include/types/address.h
hilti/runtime/src/types/address.cc
spicy/lib/spicy.spicy
tests/spicy/lib/parse-address.spicy

public function parse_address(s: string) : addr;
public function parse_address(b: bytes) : addr;
Closes #1294.

Add library function to parse an address from string or bytes.

---

hilti/runtime/src/tests/regexp.cc
hilti/runtime/src/tests/stream.cc
hilti/runtime/src/types/stream.cc
tests/Baseline/spicy.types.unit.synchronize-on-gap/output

To compute the next `View` in `advanceToNextData` after a gap chunk we would previously compute offsets incorrectly in that we would implicitly assume that the begin of the original `View` started with zero offset. This is unlikely true for any but the most trivial cases and often caused e.g., resynchronization to jump to incorrect offsets much after the correct position.
With this patch we now use a correct offset computation.
Closes #1303.

Fix incorrect offset computation in `advanceToNextData`.

---

hilti/runtime/src/tests/regexp.cc

This test was originally developed against the version on `main` (`doctest-2.4.9`), but produced errors with the version on this branch.
This patch slightly adjusts the test code in non-functional way so it can build on this branch as well.

Fix test for doctest-2.4.8.

---

doc/autogen/types/integer.rst
hilti/toolchain/include/ast/operators/signed-integer.h
hilti/toolchain/include/ast/operators/unsigned-integer.h
hilti/toolchain/src/compiler/codegen/operators.cc

We previously just passed this through without explicit type checking which caused these casts to be undocumented.

Explicitly type integer to boolean cast.

---

hilti/runtime/include/util.h
hilti/runtime/src/util.cc

We previously would always search for _any occurrence_ of `prefix` in the given string and only later check whether it was at the beginning; this could have meant potentially lots of work for long input strings.
With this patch we examine at most the first `prefix.size()` characters of the string.

Improve efficiency of `startsWith` for long inputs.

---

doc/programming/examples/_parse-bitfield-enum.spicy.output
doc/programming/parsing.rst

We now use `\xNN` with `printf` here. While that's technically not portable, it's much more readable and it works in the settings where we usually generate the docs. Indeed, we already rely on that in a couple other places as well.
Closes #1298.

Fix/clarify bitfield docs.

---

doc/programming/language/types.rst

This seems too small to open a PR, but, oh well.

Fix docs for enum using semicolon instead of comma.

---

hilti/runtime/CMakeLists.txt

We previously would only install the nlohmann header with forward declaration while in `hilti/rt/json.h` we include the full header. With that it was impossible to include this header in user code.
This patch makes sure we install the full header as well.

Install full nlohmann JSON header as well.

---

spicy/runtime/include/unit-context.h
spicy/runtime/src/tests/unit-context.cc

Not adding this in the first place broke e.g., `-X flow` or `-X trace`.

Add stringification to UnitContext.

---

hilti/toolchain/include/compiler/jit.h
hilti/toolchain/src/compiler/jit.cc
tests/spicy/tools/spicyc-ccache-data-race.spicy

We previously would not create unique names for different JIT invocations if they came from the same directory. This causes issues if the same module is imported into different analyzers where previously we would generate the same C++ and object file name. Different JIT runs could then race on the same output files and e.g., remove each others inputs/outputs. As far as I can tell this was very unlikely to produce incorrect behavior at runtime.
We now include all input files from a JIT run in the JIT has. With that above race is not possible anymore.

Remove potential race during JIT when using `HILTI_CXX_COMPILER_LAUNCHER`.

---

hilti/toolchain/src/compiler/unit.cc

With, e.g., `spicyz -L /x/y/z`, we used to append the given module
path to the internal system paths, so that it was searched last. This
change turns around the priority to search `/x/y/x` first, before the
internal ones. That seems both more useful and more intuitive.

Search user module paths before system paths.

---

hilti/runtime/include/exception.h
hilti/runtime/src/exception.cc
hilti/runtime/src/tests/to_string.cc
hilti/toolchain/src/compiler/codegen/types.cc
spicy/runtime/include/driver.h
spicy/runtime/include/mime.h
spicy/runtime/include/sink.h
spicy/runtime/include/unit-context.h
spicy/runtime/src/sink.cc

We were a bit inconsistent in the structure of exceptions that could
happen during runtime, making it hard for host applications for
consistently handle trouble. We tweak this, as follows:
- We now only have two general subcategories of exceptions under the
top-level `hilti::rt::Exception`:
- `RuntimeError`: non-fatal errors that mean a host
applications cannot complete the current line of processing,
but can otherwise continue. This is the main exception that
host applications should catch, and then proceed
appropriately.
- `UsageError`: fatal errors that indicate something about
using the runtime environment was fundamentally wrong, and a
host application should abort.
- Almost all other exceptions are now derived from `RuntimeError`,
including Spicy's `ParseError` and …

Streamline runtime exception hierarchy.

---

hilti/runtime/include/init.h
hilti/runtime/src/init.cc
hilti/runtime/src/library.cc

This can be used if triggering it through a static constructor isn't reliable.
(No test, we'll use this from inside Zeek and will notice there if
something breaks.)

 Provide ability to initiate runtime's module-pre-init phase manually.

---

hilti/toolchain/src/compiler/jit.cc
tests/hilti/tools/hiltic-jit-cc-input.cc

We previously would derive the name of the object file to generate for a given C++ input file directly from the input filename by just replacing the extension. This caused us to generate object files directly next to C++ files added explicitly to the JIT job. Multiple jobs using the same C++ input file could then race on the object file.
With this patch we make sure that object files are always generated with taking the JIT has into account. We also fix the location of object files to always be in a system temp directory.
Closes #1367.

Use unique filename for all object files generated during JIT.

---

hilti/toolchain/src/compiler/jit.cc

We used to append the paths from `HILTI_CXX_INCLUDE_DIRS` path to the
internal default include paths, so that they were searched last. This
change turns around the priority to search them first. That seems both
more useful and more intuitive.
Addresses https://github.com/zeek/spicy-plugin/issues/134.

Search `HILTI_CXX_INCLUDE_DIRS` paths before default include paths.

---

hilti/runtime/include/types/stream.h

This is flagged by `-Wsign-compare` which we do not typically activate.

Fix sign-unsigned comparison.

---

.cirrus.yml

Since the Zeek container image is based on debian-11 this allows testing against Spicy versions from branches in zeek/spicy-plugin.
Closes zeek/spicy-plugin#169.

Build debian-11 instead of centos stream 8 in CI.

---

.cirrus.yml

Without explicitly setting reupload_on_changes, the caches are never updated due to a constant fingerprint_script.
Found while looking at the CI output and finding 46Mb being a rather small ccache size.
echo $CIRRUS_TASK_NAME-$CIRRUS_OS
docker_debian11-linux
Downloaded 46Mb in 0.484147s.
Cache hit for ccache-05b8329b...

Set reupload_on_changes for ccache caches.

---

hilti/runtime/src/init.cc

Setting a locale from a library can interfere negatively with the rest of the application. We previously would set a locale inside `hilti::rt::init`, but we probably do not need it at all.

Do not force locale on users of libhilti.

---

hilti/runtime/include/types/bytes.h
hilti/runtime/src/types/bytes.cc
tests/Baseline/hilti.types.bytes.decode/output
tests/hilti/types/bytes/decode.hlt

Initialize `Bytes` internal control block for all constructors.

---

.cirrus.yml

With proper caching now implementing, the linting task takes most of the time in a CI run since it executes uncacheable clang-tidy jobs. This PR only executes clang-tidy for PRs and in scheduled builds (currently: just a nightly build). This should make execute CI much faster will.

Only run lint CI task from scheduled builds or PRs.

---

doc/zeek.rst

With zeek/spicy-plugin#201 `$file` became available for protocol analyzers. This patch updates the docs to reflect that.

Update docs for changes in spicy-plugin [skip CI].

---

docker/Dockerfile.ubuntu-16

The recently released btest-1.0 requires python-3.7 while this system has only python-3.5.

Pin btest version on ubuntu-16 in CI.

---

hilti/runtime/src/types/bytes.cc
hilti/runtime/src/types/stream.cc

We used `View::data` to constructs a new `Bytes` to append from. Since we cannot reuse the temporary in the append but have to copy the data this introduced unneeded overhead. This patch inlines the low-level `View` block iteration into `Bytes::append`.
I looked at this coming from zeek/spicy-dns#7, and with that particular test case where many small views are appended the speedup is only ~1.5%. I suspect the speedup to be bigger the bigger the view we append.
In order to amortize reallocation costs I also looked into aggressively reserving capacity in the different `append` overloads, e.g., if the new size is bigger than the current capacity, reserve double the needed capacity in anticipation of more append operations to come. This did not make a noticeable difference, probably due to …

Avoid unneeded temporaries when appending `View` to `Bytes`.

---

hilti/toolchain/include/ast/node.h

We were using `std::move` on a temporary which prevents RVO. It also triggered a very noisy warning from gcc-13.

Fix gcc-13 warning about pessimizing move.

---

spicy/toolchain/src/compiler/codegen/codegen.cc
tests/Baseline/spicy.optimization.feature_requirements/noopt.hlt
tests/Baseline/spicy.optimization.feature_requirements/opt.hlt

When generating code for `offset()` we previously would use the difference of safe iterator which has extra code to make sure the two iterators belong to the same stream. This check can never fail when computing `offset()` so use a fast pass in that case.

Add fast pass for iterator difference in `offset()`.

---

3rdparty/CMakeLists.txt
hilti/runtime/include/intrusive-ptr.h
hilti/toolchain/include/ast/operators/tuple.h
hilti/toolchain/src/compiler/codegen/operators.cc
hilti/toolchain/src/compiler/driver.cc
hilti/toolchain/src/compiler/jit.cc
hilti/toolchain/src/compiler/optimizer.cc
hilti/toolchain/src/compiler/unit.cc
hilti/toolchain/src/compiler/visitors/coercer.cc
hilti/toolchain/src/compiler/visitors/renderer.cc
hilti/toolchain/src/compiler/visitors/resolver.cc
spicy/toolchain/include/compiler/detail/codegen/parser-builder.h
tests/hilti/statements/assert.hlt

gcc13 is part supported Zeek platforms, e.g., it comes as part of fedora-38. This PR collects a number of fixes required to build with gcc13, and also interesting issues it diagnoses around dangling references. We do not add CI here in the hope that that will be added e.g., in zeek/zeek as part of the platform support policy put forth there.

Fixes for building with gcc13

---

hilti/runtime/include/types/bytes.h
hilti/runtime/src/tests/bytes.cc

Fix stdlib exception leak in `bytes::sub`

---

.github/workflows/email-failure.yml

We previously would send out a failure notification if a run was e.g., cancelled since a PR got merged before CI completed. With this PR we now skip such "uninteresting" events (cancelled, neutral, and skipped CI conclusions).

Skip failure notifications for unsuccessfull non-error runs.

---

docker/Dockerfile.ubuntu-22

The distribution already comes with a new-enough CMake so we do not need to install one out of band.

Clean up dependencies for ubuntu-22 image.

---

hilti/toolchain/src/compiler/codegen/types.cc

We previously would always emit a `const` value when passing a `strong_ref` as a function parameter. This lead to the unintuitive error that non-const `strong_ref` parameters could not be modified or have non-const methods called on them (this would actually fail at codegen time).
With this patch we remove the special treatment of `strong_ref` parameter mutability.
Closes #1447.

Do not forcibly make `strong_ref` `in` function parameters immutable.

---

doc/autogen/types/bool.rst
hilti/toolchain/include/ast/operators/bool.h
hilti/toolchain/src/compiler/codegen/operators.cc
tests/hilti/types/bool/operators.hlt

Add bitwise operators `&`, `|`, and `^` for booleans.

---

spicy/toolchain/src/compiler/visitors/resolver.cc

warning: comparison of integer expressions of different signedness
Debian Bullsye, gcc (Debian 10.2.1-6) 10.2.1 20210110.

Fix signedness warning.

---

doc/requirements.txt

This fixes the unavailability of search on [RTD](https://docs.zeek.org/projects/spicy/en). The related sphix_rt_theme issue is https://github.com/readthedocs/sphinx_rtd_theme/issues/1452. A temporary preview is available [here](https://docs.zeek.org/projects/spicy/en/topic-bbannier-rtd-search/).

Fix search on RTD

---

doc/programming/parsing.rst

Instead of decorating many fields with `if` conditions for certain grammars a simpler approach can be to use a unit switch statement with branch-by-expressions. Add a link to unit switch from the conditional parsing section.

Mention unit switch statements in conditional parsing docs.

---

hilti/toolchain/src/compiler/driver.cc

This flag was intended and always documented as a toggle, but instead implemented as an argument taking a value (which was never evaluated). This patch fixes the implementation to align with itend and documentation.

Fix handling of `--show-backtraces` flag.

---

hilti/runtime/src/tests/to_string.cc
hilti/runtime/src/types/bytes.cc

This was pointed out by Simeon Miteff in #1384.

Fix stringification of `DecodeErrorStrategy`.

---

spicy/toolchain/src/compiler/codegen/codegen.cc
tests/spicy/types/unit/offset.spicy

We declared this method to return an iterator, but potentially returned an optional iterator. This patch add an additional deref so we get the correct value.
Closes #1508.

Fix returned value for `<unit>.position()`.

---

.readthedocs.yaml

Doxygen documentation is likely not relevant for users and hides results they are looking for. Also, Doxygen already comes with its own search which is reachable the developer documentation.
Closes #1516.

Do not include generated Doxygen documentation in RTD search results

---

doc/programming/language/error-handling.rst

The docs previously made it sound as if exceptions could potentially be swallowed with `on %error` handlers. Since this is currently not supported, but a often requested feature, clarify the docs to not stir up too much anticipation.

Clarify error handling docs [skip CI].

---

doc/programming/extending.rst
doc/toolchain.rst
hilti/toolchain/src/compiler/jit.cc
tests/hilti/hiltic/jit/cxx-flags.hlt

This adds a magic environment variable `HILTI_CXX_FLAGS` which if set specifies compiler flags which should be passed during C++ compilation after implicit flags. This could be used to e.g., set defines, or set low-level compiler flags.
Even with this flag, for passing include directories one should still use `HILTI_CXX_INCLUDE_DIRS` since they are searched before any implicitly added paths.

Add support for passing arbitrary C++ compiler flags.

---

CMakeLists.txt

Zeek's configure sets Python_EXECUTABLE has hint, but Spicy is using find_package(Python3) and would only use Python3_EXECUTABLE as hint. This results in Spicy finding a different (the default) Python executable when configuring Zeek with --with-python=/opt/custom/bin/python3.
Switch Spicy over to use find_package(Python) and add the minimum version so it knows to look for Python3.

Use find_package(Python) with version.

---

doc/scripts/spicy-pygments.py

We previously would not declare that the Spicy pygments highlighter is safe to execute in parallel (reading or writing of sources). Sphinx then assumed that the extension was not safe to run in parallel and instead ran jobs sequentially.
This patch declares the extension as able to execute in parallel. Since the extension does not manage any external state this is safe.

Declare Spicy pygments extension as parallel-safe. [skip CI]

---

hilti/toolchain/include/compiler/jit.h
hilti/toolchain/src/compiler/jit.cc

This works around a silent failure in reproc where it would refuse to run on systems which huge rlimits for the number of open files. We have seen this hit on huge production boxes.

Artifically limit the number of open files.

---

.github/dependabot.yml

This add dependabot configs for updating Git submodules and GH actions.

Add GH dependabot config. [skip CI]

---

hilti/runtime/include/types/stream.h
hilti/runtime/src/types/stream.cc

Replace recursive deletion with explicit loop to avoid stack overflow.

---

hilti/runtime/src/tests/stream.cc
hilti/runtime/src/types/stream.cc

Previously we would trigger an infinite loop if one tried to trim before the head chunk of a stream. In praxis this seem to have been no issue due to #1549 and us emitting way less calls to trim than possible.
This patch adds an explicit check whether we need to trim anything, and exits the low-level function early for such cases.
Closes #1554.

Fix potential infinite loop when trimming data before stream.

---

3rdparty/CMakeLists.txt
CMakeLists.txt

When not setting an ASM compiler we might end up configuring Clang as C compiler, but GCC as ASM compiler. The code in `3rdparty/fiber` then causes Clang-only flags like `-Weverything` to be passed to GCC (which does not understand it).
The way we need to do this is subtle. We need to rely on `3rdparty/fiber` to explicitly `enable_language(ASM)` and not set it as a project language to work around `find_package(BISON)` breaking if `CMAKE_ASM_COMPILER` is set. By removing ASM from project languages and setting the ASM config after Bison was found, but before we configure `3rdparty/fiber` things seem to work as intended.

Explicitly set ASM compiler.

---

hilti/runtime/include/types/stream.h
hilti/runtime/src/types/stream.cc

Trimming `Chunk`s (always from the left) causes a lot of internal work with only limited benefit since we manage visbility with `stream::View`s on top of `Chunk`s anyway.
This patch removes trimming inside `Chunk`s so now any trimming only removes `Chunk`s from `Chain`s, but does not internally change individual `Chunk`s anymore. This might lead to slighly increased memory use, but callers usually have that data in memory anyway.
Closes #1571.

Remove trimming inside individual chunks

---

ci/run-ci

This is a follow-up to 2b92da596631ff1a29b7deac05e00faaad9305f3.

Remove check of Zeek docs in Cirrus cron config [skip CI]

---

hilti/runtime/include/types/vector.h

Iterating over hilti::Vector is quite expensive due to the weak_ptr::lock() calls. For unsafe uses, allow access to the underlying std::vector for faster raw iteration speed.
---
Change on the Zeek side: https://github.com/zeek/zeek/pull/3491

Allow unsafe Vector iteration over underlying std::vector.

---

hilti/toolchain/src/compiler/visitors/coercer.cc
tests/spicy/types/set/const-set.spicy

Allow for unresolved types for set `in` operator.

---

hilti/runtime/include/types/bytes.h
hilti/runtime/include/types/vector.h

Vector and Bytes currently allocate and de-allocated a shared_ptr as a "control block" unconditionally.
This results in an extra malloc and free as well as atomic instructions during destruction. This control block is only required when "safely" iterating, but that may never happen.
Applying this change and testing with a fairly large analyzer, execution time is reduced from 20.6 seconds to ~17.3~ 19.5 seconds, some ~16%~ 5%.
A further step might be to implement a custom control block class to avoid the atomic instructions altogether. Also, the StrongReferene and ValueReference use shared_ptr, showing significantly in profiles. Their usage should likely be revisited, too.
---
mutable and const_cast. Happy to hear how to do that nicer :-)

Vector/Bytes: Lazily allocate shared_ptr _control

---

hilti/runtime/include/types/stream.h

The main changes in this patch are adding of move constructors for types used heavily in generated code (in C++17 if a type declares any constructor no implicit move constructor is generated anymore). This cuts about 4% from the runtime for a huge internal parser we have. Changes here are motivated by benchmark results and I didn't attempt a sweeping audit.

Misc performance improvements

---

hilti/runtime/include/types/stream.h
spicy/toolchain/CMakeLists.txt

It looks like using a `IntrusivePtr<const T>` interferes with default'ed move constructors and assignment operators so that the non-move versions are called. This can incur additional overhead.
This patch simply gets rid all `IntrusivePtr<const T>` in favor of `IntrusivePtr<T>` which does not seem to show this issue. It might be possible to instead adjust something e.g., `ManagedObject` so `IntrusivePtr` does not regress when holding semantically `const` values though.
For a big internal parser this shows runtime improvements up to 2%.

Remove use of `IntrusivePtr` over `const`.

---

hilti/runtime/include/types/stream.h
hilti/runtime/src/tests/stream.cc

While we already had a fast path to extract data out of `View`s consisting of a single chunk we still would use a potentially inefficient approach when extracting from `View`s over multiple chunks.
This patch uses the same optimized handling for both cases.
Closes #1628.

Avoid potentially inefficient data access in `View::extract`.

---

.cirrus.yml
doc/autogen/types/string.rst
hilti/toolchain/include/ast/operators/string.h
hilti/toolchain/src/compiler/codegen/operators.cc
tests/hilti/types/string/operators.hlt

This allows appending to a `string` without having to allocate a new string. This might perform better most of the time.
Closes #1500.

Add `+=` operator for `string`.

---

hilti/runtime/include/types/string.h
hilti/runtime/src/types/string.cc
hilti/toolchain/src/compiler/codegen/operators.cc
tests/hilti/types/string/operators.hlt

While we defined `string`'s size operator to return an `uint64` and documented that it returns the length in codepoints, not bytes, we still generated C++ code which worked on the underlying bytes (i.e., it directly invoked `std::string::size` instead of using `hilti::rt::string::size`).

Fix type of generated code for `string::size`.

---

.github/workflows/email-failure.yml
.github/workflows/email-success.yml

We not using the correct field here, https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#check_suite.

Fix incorrect check_suite type in GH actions [skip CI].

---

spicy/toolchain/src/compiler/visitors/validator.cc

This validator was intended to reject incorrect parsing of vectors but instead ending up rejecting all vector parsing if the vector elements itself produced vectors. Since this code has no test and it seems to have no clear purpose this patch drops this validation.
Closes #1522.

Drop overzealous validator.

---

scripts/autogen-type-erased

At least on my platform with python-3.12.2 the previous code produced a warning
../scripts/autogen-type-erased:137: SyntaxWarning: invalid escape sequence '\{'
i = re.search("(.*) *with *default *(\{.*)$", s)

Fix stray Python escape sequence.

---

hilti/toolchain/src/compiler/optimizer.cc
tests/Baseline/hilti.optimization.const/noopt.hlt
tests/Baseline/hilti.optimization.const/opt.hlt
tests/hilti/optimization/const.hlt

While loops with constant conditions are unlikely to occur in code generated by us, but could appear in user code. Cleaning them up is simple and cheap, so this patch implements a pass which simplifies them.

Simplify `while` loops over constant conditions.

---

spicy/toolchain/include/ast/types/unit.h
spicy/toolchain/src/ast/operators/unit.cc
spicy/toolchain/src/ast/types/unit.cc
spicy/toolchain/src/compiler/resolver.cc
tests/spicy/types/unit/context-unit-func-param.spicy

- **Infer constness of `<unit>.context()` from that of `<unit>`.**
- **Move inferring of a unit's context type into the resolver.**

`context()` constness fix

---

.pre-commit-config.yaml
doc/conf.py
doc/scripts/spicy-doc-to-rst
doc/scripts/spicy-pygments.py
doc/scripts/spicy.py
hilti/runtime/src/exception.cc
spicy/toolchain/bin/spicy-dump/main.cc
tests/Scripts/stray_baselines.py

This PR makes a pass over our Python scripts. We add a [simple linter and formatter](https://docs.astral.sh/ruff/). We also modernize scripts with [`pyupgrade`](https://pypi.org/project/pyupgrade/).
While we are at it we also bump some other pre-commit hooks.

Pass over Python scripts

---

.cmake-format.json
ci/fuzz/CMakeLists.txt

When generating fuzzer binaries we previously would generate parser and linker code in two invocations, one for the module's C++ code with `-c` and one for the linker code with `-l` As of
28437292fcf01cb1602e0318924cd7c78f5429fe this generates code which often fails to link due to missing symbols (this seems to be due to us not including code from the `filter` module in the single-file C++ output anymore).
This patch reworks to code to switch from using two separate `spicyc` invocations with `-c` and `-l` to emitting all sources at once with `-x`. This requires some changes to the CMake function generating the targets as we need to statically name all inputs to `add_executable` which generates code for each module and the linker file. We also rename the binaries in the process.

Fix fuzzer builds for reworked AST.

---

hilti/toolchain/include/ast/ast-context.h
hilti/toolchain/include/ast/declarations/module.h
hilti/toolchain/include/compiler/detail/codegen/codegen.h
hilti/toolchain/include/compiler/detail/cxx/linker.h
hilti/toolchain/include/compiler/unit.h
hilti/toolchain/src/ast/ast-context.cc
hilti/toolchain/src/ast/declarations/module.cc
hilti/toolchain/src/compiler/codegen/codegen.cc
hilti/toolchain/src/compiler/cxx/linker.cc
hilti/toolchain/src/compiler/driver.cc
hilti/toolchain/src/compiler/unit.cc
tests/Baseline/hilti.ast.basic-module/output
tests/Baseline/hilti.ast.imported-id/output
tests/Baseline/hilti.hiltic.print.import/output
tests/Baseline/hilti.hiltic.print.import/output2

We used to potentially codegen modules multiple times. Now we cache a
module's generated C++ code inside the AST node the first time we
create it. From there, we can then easily reuse it later, in
particular when needing to import its declarations into another
module. Internally, we switch storage for `cxx::Unit` to shared
pointers, and tweak the debug logging a bit for better readability in
this new model.

Rework order of C++ module codegen.

---

hilti/toolchain/src/compiler/cxx/elements.cc

GCC's analysis assumes that `strncpy` should always produce null-terminated strings. For the use case here this is not the case as we store the resulting string into a hand-sized `std::string` later.
Work around the diagnostic by using `memcpy` (and surpressing a `clang-tidy` warning triggered by that).

Fix GCC false positive around `strncpy` use.

---

hilti/toolchain/src/compiler/codegen/codegen.cc
spicy/toolchain/include/compiler/detail/codegen/productions/counter.h
spicy/toolchain/src/compiler/codegen/grammar-builder.cc
spicy/toolchain/src/compiler/codegen/production.cc
spicy/toolchain/src/compiler/codegen/productions/switch.cc

When switching to the new AST implementation a few instances snuck in
where codegen became non-deterministic. This seems to have exclusively
affected symbol indentifiers generated from productions where we would
accicentially output addresses instead of values. This patch fixes these
instances.

Fix a few instances where codegen was non-deterministic.

---

hilti/toolchain/include/ast/expressions/resolved-operator.h
hilti/toolchain/include/ast/operators/common.h
hilti/toolchain/include/ast/operators/reference.h
hilti/toolchain/src/compiler/codegen/operators.cc
hilti/toolchain/src/compiler/coercer.cc
spicy/toolchain/src/compiler/codegen/codegen.cc
tests/spicy/types/unit/context-inout.spicy

- **Unify code generation for `new`.**
- **Mark automatic derefs inside the operator's AST node.**
- **Fix `new` passing a unit reference to an `inout` unit parameter.**
Closes #1719.

Fix inout unit parameter with reference

---

.clang-tidy
hilti/runtime/include/types/bitfield.h
hilti/toolchain/src/compiler/codegen/ctors.cc
tests/Baseline/spicy.types.bitfield.parse-and-convert/output
tests/hilti/types/bitfield/convert.hlt
tests/spicy/types/bitfield/parse-and-convert.spicy

- **Suppress new clang-tidy warnings.**
- **Fix `&convert` typing issue with bit ranges.**

Fix `&convert` on bit range

---

hilti/runtime/include/types/stream.h
hilti/runtime/src/types/stream.cc
spicy/runtime/src/driver.cc

This is a bit experimental still. It seems to work as intended,
however I'm not sure yet if it's worth the complexity. On the traces
I've been trying so far (some DNS and TLS traffic), CPU usage actually
remains about the same (not worse, not better). But memory usage
improves about 4-5% for TLS (while it remains about the same for DNS).
However, this could all be different with larger, more realistic
input; and also better handle some degenerated corner cases. Plus, if
nothing else this addresses the occasional concern of "Spicy copying
all data" ...
- **Extend stream API to allow for chunks that don't own their data.**
- **Cache previously trimmed chunks inside stream for reuse.**
- **Give stream a method to reset it into freshly initialized state.**
- **Update Spicy runtime driver to …

Avoid copying input data where we can

---

hilti/runtime/CMakeLists.txt
hilti/runtime/include/deferred-expression.h
hilti/runtime/include/libhilti.h
hilti/runtime/src/tests/deferred-expression.cc
hilti/toolchain/include/ast/builder/builder.h
hilti/toolchain/include/ast/builder/node-factory.h
hilti/toolchain/include/ast/expressions/all.h
hilti/toolchain/include/ast/expressions/deferred.h
hilti/toolchain/include/ast/visitor-dispatcher.h
hilti/toolchain/src/compiler/codegen/expressions.cc
hilti/toolchain/src/compiler/resolver.cc

This reverts and updates the previous change to remove
`rt::DeferredExpression`. Turns out we still need it for the Zeek
integration.
- **Revert "Remove support for deferred expressions."**
- **Remove `std::functional` from `DeferredExpression`.**

Bring back `DeferredExpression`

---

spicy/runtime/include/configuration.h

We did not properly initialize pointer values for accept and decline hooks. In downstream code they then appeared to be set when they were in fact not.
With this patch we initialize them with proper defaults.

Fix behavior for unset accept and decline hooks.

---

hilti/toolchain/src/compiler/resolver.cc

We would previously assume that operand types in `map`'s `in` operator were always resolved which is not the case, e.g., for this code `x.b` might be unresolved:
```ruby
public type X = unit {
var a: map<bytes, bytes>;
: Y(self);
};
type Y = unit(x: X) {
on %done { b"" in x.a; }
};
```
The implementation of `set`'s `in` operator already accommodated this by defering until all types are resolved. This changes the implementation for `map`'s `in` to follow a similar pattern.
Closes #1743.

Use a checked cast for `map`'s `in` operator.

---

doc/programming/language/packing.rst

Fix a typo in the `unpack` docs for `real` values where the template argument to `unpack` was `uintX|intX` instead of `real`.

Fix a typo in pack/unpack docs

---

hilti/toolchain/include/compiler/detail/parser/driver.h

When building Spicy as part of Zeek against the Homebrew flex-2.6.4 I
saw linker errors after f523256,
```
ld: Undefined symbols:
HiltiFlexLexer::LexerInput(char*, unsigned long), referenced from:
vtable for hilti::detail::parser::Scanner in driver.cc.o
HiltiFlexLexer::LexerOutput(char const*, unsigned long), referenced from:
vtable for hilti::detail::parser::Scanner in driver.cc.o
```
It is still not clear to me how this error comes about, but the change in
this patch seems to address the issue.

Fix Flex linker error when building as part of Zeek.

---

.readthedocs.yaml

Since this version was first released readthedocs has revamped their approach to project configuration and also become much stricter in what they allow. Due to that the docs for the latest 1.8 release do not build anymore.
This copies the RTD config from `main` into this branch.

Update RTD config to latest version.

---

hilti/toolchain/src/compiler/cxx/unit.cc
tests/Baseline/hilti.hiltic.print.globals/output
tests/Baseline/hilti.hiltic.print.globals/output2
tests/Baseline/hilti.hiltic.print.import/output
tests/Baseline/hilti.hiltic.print.import/output2
tests/Baseline/hilti.types.real.nops/output
tests/hilti/expressions/const-from-func.hlt

The changes ordering of the emitted global declarations so that
functions now come first, allowing them be used inside subsequent
constant initializations.
Closes #1745.

Fix C++ initialization of global constants through global functions.

---

hilti/toolchain/src/compiler/codegen/ctors.cc

When unrolling constructors of collections we previously would always capture explicitly so that container elements could reference other variables in the scope. This breaks for `const` variables which are emitted at non-local scope (into a namespace); the lambda performing the initialization would also be a non-local and non-local lambdas are not allowed to capture anything (they do not live in a scope after all).
This means that we cannot capture for such lambdas at all which seems to be an issue -- after all with that it seems impossible to support constructors of collections which reference other `const`s. Fortunately C++ lambdas at non-local scope implicitly capture other non-locals already and they do not need to be captured explictly. This allows for a rather simple fix.
Closes …

Fix generated code for huge `const` collections.

---

spicy/toolchain/src/compiler/parser/parser.yy
spicy/toolchain/src/compiler/parser/scanner.ll
tests/spicy/types/network/ops.spicy

`network` was not recognized by the scanner.

Fix Spicy's support for `network` type.

---

.github/workflows/email-failure.yml
.github/workflows/email-success.yml

In order to detect whether to send out a failure email we previously would check that the action conclusion contained certain statuses. This check seems to have been nonsensical as we only notified for benign failure reasons (the check would have made a little more sense if negated, but would have then also notified on successes).
With this patch we instead explicitly enumerate the failure conclusions to trigger on, see
https://docs.github.com/en/webhooks/webhook-events-and-payloads#check_suite--check_suite-object for the full list of conclusions.

Fix when GH `email-failure` action sends notification.

---

doc/toolchain.rst

Document spicy-driver's `@gap` for batch input.

---

.pre-commit-config.yaml
hilti/runtime/include/global-state.h
spicy/toolchain/bin/spicy-dump/printer-json.h
spicy/toolchain/bin/spicy-dump/printer-text.h

Add a missing include for `locale_t`. Without this patch this fails to build with e.g., gcc-12 on macos.

Add missing include.

---

hilti/toolchain/include/base/cache.h
hilti/toolchain/src/compiler/cxx/unit.cc

Prevent defining already forwarded constants.

---

hilti/toolchain/include/ast/declarations/imported-module.h
hilti/toolchain/include/ast/declarations/module.h
hilti/toolchain/src/ast/ast-context.cc
hilti/toolchain/src/compiler/unit.cc
spicy/toolchain/src/compiler/codegen/codegen.cc
tests/Baseline/hilti.ast.imported-id/output
tests/Baseline/spicy.types.unit.hooks-across-imports/.stderr
tests/spicy/codegen/import-cycle.spicy

Our tracking of module dependencies could end up mixing `.spicy` and `.hlt`
modules when the former transitioned into the latter. Closes #1784.

Fix import HILTI vs Spicy confusion.

---

hilti/toolchain/src/compiler/optimizer.cc
tests/spicy/optimization/file-order.spicy

We previously would evaluate whether a unit field or method was required
by an optional feature before we had finished collecting all feature
requirements. This behavior was fine when we were visiting individual
modules' AST one by one, but breaks with #1462 were we changed using a
single AST to hold all modules.
This patch defers transformations until all feature requirements have
been collected.

Defer start of feature-dependent transformations to a later point.

---

CMakeLists.txt
doc/installation.rst

We previously needed this since during the build we were generating files with Python. This is not the case anymore.

Do not search for Python in CMake setup.

---

spicy/runtime/src/sink.cc
spicy/runtime/src/tests/parser.cc
tests/Baseline/spicy.types.sink.reassembler.overlap/output
tests/spicy/types/sink/reassembler/overlap.spicy

If no sink hooks were specified by the user trying to invoke them would raise a `std::bad_function_call` previously since we did not have explicitly guard the code. With #1736 we us infrastructure with less implicit checks so we need to handle the absence of a value ourself since otherwise we might end up dereferencing a nullptr.

Guard access to sink hooks.

---

hilti/toolchain/src/compiler/optimizer.cc
tests/spicy/optimization/issue-1808.spicy

The optimizer's `FunctionVisitor` computes whether a function is used or required by any feature. Since recently we now hold all modules in a single AST. This means that we need at least one full pass through the AST to collect feature constants so we can decided whether a function is required by a feature and cannot be elided. The initial implementation of this used explicit control flow, but this is error-prone like seen in #1808.
This patch removes the explicit control flow and instead checks whether we have discovered any new feature constants. With that the optimizer pass converges again.
Closes #1808.

Fix non-converging optimizer pass for used functions.

---

hilti/toolchain/include/ast/ast-context.h
hilti/toolchain/include/ast/declarations/module-uid.h
hilti/toolchain/src/ast/ast-context.cc
hilti/toolchain/src/compiler/driver.cc
tests/hilti/ast/imported-twice.hlt

We already computed a `unique` `ID` value for each module to allow
declaring the same `ID` name multiple times; we however did not
consistently use that value in the implementation of `module::UID`
equality and hash operators which is addressed by this patch.
Closes #1813.

Fix equality implementation of module UID.

---

hilti/runtime/src/tests/bytes.cc
hilti/runtime/src/types/bytes.cc
hilti/toolchain/src/ast/operators/bytes.cc
tests/hilti/types/bytes/to-int.hlt

* Reject empty byte ranges for `to_uint(ByteOrder)`.
* Fix shifting of 32bit value, causing `to_int(ByteOrder)` to return bogus values.

to_int() ubsan fixes

---

hilti/toolchain/src/ast/scope-lookup.cc

Prevent null ptr dereference when looking on nodes without `Scope`.

---

hilti/toolchain/include/ast/declarations/module-uid.h

Function parameters still shadown members in C++. This is a fixup of c3abbbe8eb28d1e2cee5b58b19e1a30710b38853.

Fix use of move'd from variable.

---

hilti/toolchain/src/compiler/cxx/linker.cc
tests/hilti/codegen/library-version.hlt

We need them at their original values because that's what the runtime
lbirary is hard-coded to expect.
Closes #1823.

Don't qualify magic linker symbols with C++ namespace.

---

hilti/toolchain/src/compiler/optimizer.cc
tests/Baseline/spicy.optimization.unused-types/log
tests/Baseline/spicy.optimization.unused-types/opt.hlt

We were no longer marking types as used that are referenced through a
type name.
Closes #1831.

Fix optimizer regression.

---

hilti/toolchain/CMakeLists.txt
hilti/toolchain/include/ast/type.h
hilti/toolchain/src/ast/ast-context.cc
hilti/toolchain/src/config.cc.in

One more branch we had to follow to track down all dependencies
between global declarations: external qualified types.
Closes #1835.

Fix computation of declaration dependencies.

---

.update-changes.cfg

We rely on CI to create releases, so having `[skip CI]` in our update-changes config was always a hassle which needed to be edited out when creating a release (just tagging would autocommit with the message template without a way to change the commit message before tagging).
Drop this part to make releases easier and less error prone.

Do not by default skip CI in update-changes cfg. [skip CI]

---

spicy/toolchain/src/compiler/codegen/parser-builder.cc
tests/spicy/types/unit/skip-unit.spicy

For unit parsing with `skip`, we would create a temporary instance
but wouldn't properly initialize it, meaning for example that
parameters weren't available. We now generally fully initialize any
destination, even if temporary.
Closes #1852.

Fix `skip` with units.

---

hilti/toolchain/src/config.cc.in

Compile generated C++ with `-O0` in debug mode.

---

.pre-commit-config.yaml

The names we used have been deprecated since some time, see https://github.com/pre-commit/pre-commit/issues/2732.

Stop using deprecated pre-commit stage names.

---

doc/programming/language/statements.rst

Not too sure if it was left off for a reason, but seems like a lot changed since this was added. I think if `break` is documented, `continue` should be.

Document `continue` statements

---

hilti/runtime/include/context.h
hilti/runtime/include/fiber.h
hilti/runtime/include/logging.h
hilti/runtime/src/logging.cc
hilti/runtime/src/tests/fiber.cc

This fixes potential location mix-ups when switching between fibers.
Note that we still need a context-wide fallback location as well
because we're not always running inside a fiber.
I ran a performance comparison before/after and couldn't measure a
difference. Looks like using TLS storage was a case of premature
optimization.
Closes #1868.

Associate source code locations with current fiber instead of current thread.

---

hilti/toolchain/include/compiler/validator.h
hilti/toolchain/src/compiler/codegen/ctors.cc
hilti/toolchain/src/compiler/validator.cc
spicy/toolchain/src/compiler/validator.cc
tests/spicy/types/unit/convert-with-type-param.spicy

Fix usage of `&convert` with unit's requiring parameters.
The generated code needs to create a temporary instance of the type,
but doesn't have any arguments to provide to it. But that's ok, and we
now let the validation pass and just instantiate a default-constructed
instance.
This is a bit hackish due to needing to shift things around to the
right places, but couldn't think of a better fix.
- **Factor out logic to validate arguments given to a type.**
- **Fix usage of `&convert` with unit's requiring parameters.**

Fix usage of `&convert` with unit's requiring parameters.

---

spicy/runtime/src/base64.cc

Fixes #1891
I still haven't reproduced the issue, but this seems to fix it. Honestly, I don't even know what really caused it. It's just probably good to use an explicit cast to get the overload we want rather than relying on user defined conversions.

Fix GCC 11 compilation failure.

---

.pre-commit-config.yaml
.typos.toml
CHANGES
hilti/runtime/src/tests/reference.cc
hilti/runtime/src/types/address.cc
hilti/runtime/src/types/regexp.cc
hilti/runtime/src/types/time.cc
hilti/toolchain/src/base/util.cc
tests/spicy/tools/spicyc-ccache-data-race.spicy

I am unsure why we included this in the first place. I suspect it was a
leftover from development.

Remove stray removal of directory in /tmp in test.

---

doc/programming/examples/_parse-websocket-bitfield.spicy
doc/programming/parsing.rst

Going through docs to make sure attributes line up for validation and I noticed that this snippet won't compile (missing semicolons, closing brace, and import).
Also changed it to 4 space indents because that's what code around it is

Fix doc code snippet that won't compile.

---

doc/scripts/autogen-docs

We would previously exit early from this script if we could not generate the architecture diagram for which we needed the Python `diagrams` package (which implicitly depends on `dot` as well). This setup made it impossible to automatically update generated documentation unless one had both `diagrams` and `dot` installed. Additionally the generated `architecture.svg` was not stable across different versions of `dot`.
This patch rewrites `./doc/scripts/autogen-docs` so it can update documentation even if the dependencies for diagram generation are present. Since the `diagrams` output depends on dot (and its version) I currently see no stable, platform-indepdendent way to generate the diagram in a pre-commit hook, so we do not even attempt to make `diagrams` available to the pre-commit hook. …

Make sure `autogen-docs` pre-commit hook can always run in CI

---

tests/spicy/rt/time.spicy

This test still compares the current time against hardcoded times to check ordering. Extend the upper value so this test passes for the next ~200 years.

Keep test `spicy.rt.time` working for the next 200 years.

---

LICENSE
doc/conf.py

It may be worth going through the files to change it to something similar as well, but for now I'll just put this in as a minimal amount. This covers the most forward-facing parts, at least :)
what docs copyright looks like now:

Remove copyright years [skip CI].

---

doc/programming/language/types.rst
hilti/runtime/include/types/regexp.h
hilti/runtime/src/tests/bytes.cc
hilti/runtime/src/tests/regexp.cc
hilti/runtime/src/tests/to_string.cc
hilti/runtime/src/types/regexp.cc
hilti/toolchain/include/ast/builder/builder.h
hilti/toolchain/include/ast/builder/node-factory.h
hilti/toolchain/include/ast/ctors/regexp.h
hilti/toolchain/src/compiler/codegen/ctors.cc
hilti/toolchain/src/compiler/parser/parser.yy
hilti/toolchain/src/compiler/printer.cc
spicy/toolchain/src/compiler/codegen/parser-builder.cc
spicy/toolchain/src/compiler/codegen/parsers/literals.cc
spicy/toolchain/src/compiler/parser/parser.yy
tests/Baseline/spicy.types.unit.switch-lahead-regexp-incremental/output
tests/hilti/codegen/type-info.hlt
tests/hilti/types/regexp/case-insensitive.hlt
tests/hilti/types/regexp/incremental-spicy-style.hlt
tests/hilti/types/regexp/set-matching.hlt
tests/spicy/types/unit/switch-lahead-regexp-incremental.spicy

By adding an `i` flag to a regular expression pattern, it will no w be
matched case-insensitively (e.g. `/foobar/i`).
This goes with https://github.com/rsmmr/justrx/pull/11, if anybody feels like reviewing that one as well.
- **Refactor regexp patterns.**
- **Bump justrx to pull in new API group matching.**
- **Switch regular expressions to new justrx API.**
- **Add support for case-insensitive matching to regular expressions.**

Add support for case-insensitive matching to regular expressions.

---

doc/host-applications.rst

The order of `ldflags` compared to the `-o` output/source file matters - linking flags should be after (I think). This took me a while to debug because I haven't seen it before and it worked on my Mac so I was confused. As-is, the documentation fails to compile for me, but with this change, the command succeeds.
Compiler is `c++ (GCC) 14.2.1 20240912 (Red Hat 14.2.1-3)`

Fix possibly-incorrect custom host compile command

---

hilti/toolchain/src/compiler/cxx/elements.cc
tests/Baseline/hilti.hiltic.print.globals/output
tests/Baseline/hilti.hiltic.print.import/output

This reverts part of https://github.com/zeek/spicy/commit/cb7336ff8d02a32fc82ec4f1c74f4606e13b8ff0: as it turns out, the Zeek
integration still needs `__visit`. I'd like to solve this differently
on the Zeek side, but have't quite gotten that to work yet. So
reverting this for now so that we don't block.

Bring back the internal `__visit` method for generated structs.

---

spicy/runtime/CMakeLists.txt
spicy/runtime/tests/benchmarks/CMakeLists.txt
spicy/runtime/tests/benchmarks/parsers.spicy
spicy/runtime/tests/benchmarks/parsing.cc

Draft PR as I work on it, but thought it might be useful/interesting.
Initial run with the two cases I ran:
```
--------------------------------------------------------------------------------------
Benchmark                                            Time             CPU   Iterations
--------------------------------------------------------------------------------------
benchmark_parser/Benchmark::WithUnit/100         12910 ns        12849 ns        55722
benchmark_parser/Benchmark::WithUnit/1000       120478 ns       120480 ns         5742
benchmark_parser/Benchmark::WithUnit/10000     1140806 ns      1140793 ns          588
benchmark_parser/Benchmark::WithUnit/100000   11261903 ns     11261919 ns           62
benchmark_parser/Benchmark::Regex/100             5099 ns         5102 ns …
```

Simple parser (micro-)benchmarking

---

doc/programming/debugging.rst
doc/programming/language/statements.rst
doc/programming/language/types.rst
doc/programming/parsing.rst

- **Document iteration over maps/set/vectors.**
- **Document `assert-exception`.**
- **Document use of `$$` inside `&{while,until,until-including}`.**
- **Add documentation on how to interpret stack traces involving fibers.**

Various documentation updates

---

doc/getting-started.rst
doc/host-applications.rst
hilti/toolchain/include/ast/node.h
spicy/runtime/include/sink.h

Also, I have a question:
Is it "an HILTI" or "a HILTI"? I picked "a HILTI"
also these are the lines highlighted by the highlight change:

Fix minor typos in comments and docs

---

spicy/runtime/tests/benchmarks/CMakeLists.txt

The manual path wouldn't work inside Zeek.

Fix a path in the CMake config for the recent benchmark.

---

hilti/toolchain/src/compiler/cxx/elements.cc
tests/Baseline/hilti.hiltic.print.globals/output
tests/Baseline/hilti.hiltic.print.import/output

This reverts commit 479b2d4bfb88c3010aba21f63db4c2c04a65216a. We now
*really* don't need this anymore since Zeek has been adapted
accordingly.

Revert "Bring back the internal `__visit` method for generated structs."

---

.pre-commit-config.yaml
hilti/toolchain/CMakeLists.txt
spicy/runtime/tests/benchmarks/CMakeLists.txt
spicy/toolchain/CMakeLists.txt

We use `SKIP_LINTING` to disable running tools like `clang-tidy` via
CMake on generated. This is only supported with >=cmake-3.27 which is
satisfied in our CI infrastructure.
It is not really clear to me how to properly do this with earlier CMake
versions, so we simply only set this up if supported. This means that
users trying to run linters via CMake with an older version might see
diagnostics in generated code. This seems acceptable to me.

Only disable clang-tidy if CMake version supports it.

---

spicy/runtime/src/driver.cc

While we already did some handling of non-HILTI exceptions in Spicy's high-level drivers[^spicy-driver] (even though this would allow escape of exceptions not deriving from `std::exception`), we did not do the same for the lower level processing functionality in the actual driver. This is the interface used by e.g., Zeek, and already an `std::exception` thrown from a parser would lead to the exception propagating into Zeek and ultimately causing a `std::terminate` there, see e.g., [this oss-fuzz
report](https://oss-fuzz.com/testcase-detail/6088469254569984). In that particular case a call to `std::vector::reserve` exceeding the available memory caused raising of a `std::length_error`.
This patch extends the exception handling in the driver so all exceptions are handled by now transforming …

Prevent escape of non-HILTI exception in lower-level driver functions.

---

doc/development/coding-style.rst

Mainly looked at the static analysis (now linting) section, since it referenced a non-existant Makefile after #1951 
I was going to add some `clang-tidy` stuff into the configure script, but that gets weird with `-fix`

Touchup docs style section

---

hilti/toolchain/include/ast/node-tag.h

Include cstdint header to support uint8_t/uint64_t in GCC 15+

Fix compilation error for GCC15

---

cmake/Util.cmake
hilti/toolchain/CMakeLists.txt
spicy/toolchain/CMakeLists.txt

We do not seem to need any includes from Bison, but where previously adding some include path in a pretty ad hoc way. This patch performs minimal cleanup of this. There is probably the opportunity to clean up how we add dependencies with Flex and Bison (e.g., using by refactoring how we propagate this and using functionality like `add_flex_bison_dependency` at the lowest level), but I punt on that here.

Drop unnecessary Bison include from CMake function.

---

doc/Makefile
doc/index.rst

The previous link seems to have gone away some time ago.

Fix doc link to Zeek's Slack

---

ci/run-ci

This is now instead part of the release checklist.
Closes #2059.

Remove the documentation's linkcheck from CI.

---

hilti/toolchain/include/ast/builder/builder.h
hilti/toolchain/include/ast/ctor.h
hilti/toolchain/include/ast/ctors/reference.h
hilti/toolchain/include/ast/ctors/struct.h
hilti/toolchain/src/compiler/codegen/ctors.cc
hilti/toolchain/src/compiler/codegen/operators.cc
hilti/toolchain/src/compiler/codegen/types.cc
hilti/toolchain/src/compiler/coercer.cc
hilti/toolchain/src/compiler/resolver.cc
spicy/toolchain/src/compiler/codegen/codegen.cc
spicy/toolchain/src/compiler/codegen/parser-builder.cc
tests/spicy/types/tuple/self-recursive.spicy

We had cyclic dependencies partially solved through the `&on-heap`
conversion, but weren't consistently applying it to types nested
inside others.
Closes #2061.
- **Add API method to ctors to see if they create a reference.**
- **Small tweak to builder API so that we can create index expression with operands other than integers.**
- **Fix cyclic usage of units types inside other types.**

Fix cyclic usage of units types inside other types.

---

hilti/toolchain/src/compiler/codegen/codegen.cc
hilti/toolchain/src/compiler/codegen/statements.cc
spicy/toolchain/bin/spicy-doc.cc
spicy/toolchain/src/compiler/codegen/parser-builder.cc
spicy/toolchain/src/compiler/codegen/parsers/literals.cc
spicy/toolchain/src/compiler/codegen/parsers/types.cc

Round of fixes for some issues marked as being fixed but were probably missed in the awesome UI. I did not dig to find out if they're actually fine, I'd rather just shut them up :)
There are a couple of "uncaught" exceptions in `spicy-driver.cc` that may need to be manually resolved, I think they were fixed by 6fc414d? Not looking super hard, though - maybe I missed something. CIDs 1586737 & 1586307
Also fixing 1586205 caused a `stack-use-after-scope` address sanitizer issue [in CI](https://cirrus-ci.com/task/6232057568821248?logs=build#L462) so I dumped it

Coverity fixes

---

hilti/runtime/src/fiber.cc

When aborting a fiber, we need to activate it once more, to then leave
it for good by raising an `AbortException`. Problem was that that
exception ended up being caught by user code because it was derived
from `std::exception`. This change removes the base class so that the
exception is guaranteed to go back to the managing fiber code, where
we just ignore it.

Fix fiber abortion.

---

hilti/toolchain/src/compiler/codegen/operators.cc
tests/spicy/types/struct/ref-has-member.spicy

The regular member access operators already did this.
Closes #2100.

Add missing deref operations for struct try-member/has-member operators.

---

hilti/toolchain/src/compiler/optimizer.cc
tests/spicy/optimization/remove-captures-param.spicy

This caused a regression/C++ compiler error in spicy-nats.
this is the same solution as before https://github.com/zeek/spicy/pull/2083#discussion_r2174989210 - but I made it specifically only apply for `__captures`. Apparently the other tests pass because their units are public, whereas when I hit the issue I hadn't made public units stable yet.
Not sure why it only applies to `__captures` but it seems like the case.

Avoid removing `__captures` from non-public units.

---

hilti/toolchain/include/base/graph.h
hilti/toolchain/include/compiler/detail/cfg.h
hilti/toolchain/src/compiler/cfg.cc
hilti/toolchain/src/compiler/optimizer.cc

This is a followup from [this comment](https://github.com/zeek/spicy/pull/2138#discussion_r2282952585). Instead of using a set, it adds a sort to the CFG so we can traverse it the most effective way. For constant propagation, that's reverse postorder. Note that it doesn't store the result because we currently treat CFGs as pretty ephemeral, happy to change that if it seems useful
I took the mean number of iterations until convergence in `populate_dataflow` for three scenarios: unsorted, postorder, and reverse-postorder when compiling the Redis analyzer. Here are the results:
```
Mean for out-postorder: 105.69
Mean for out-reverse-postorder: 27.41
Mean for out-unsorted: 97.59
```
So reverse postorder wins pretty easily, since fewer iterations == better
I also touched up a couple parts. The …

Sort the CFG for constant propagation

---

hilti/toolchain/src/compiler/cfg.cc

From #2171
I accidentally didn't swap a condition when I changed the default to be including dataflow so the variable says to omit... oops. At least it doesn't change the logic

Fix misnamed variable [skip CI].

---

hilti/toolchain/include/compiler/detail/cxx/elements.h
hilti/toolchain/src/compiler/cxx/elements.cc
tests/hilti/codegen/struct-parameter-passing.hlt

Previously we could generate C++ moves for constructor arguments passed as references. This is semantically incorrect, but seems to have had no ill effects on code we generated. Since it could still confuse readers and static analysis tools fix this to only generate moves if the argument was passed as `copy`, but write out copies for all other argument passing. This more clearly reflects what was already happening.

Fix C++ code generation for struct parameters passed as references.
