zeek/spicy

.cirrus.yml, hilti/src/compiler/unit.cc, hilti/src/compiler/visitors/validator.cc
This PR also fixes a couple preexisting code issues.
=> Automatically trigger CI jobs

hilti/include/rt/util.h
=> Add range check to digits in Spicy's atoi_n().

.cirrus.yml, docker/Dockerfile.alpine-3.11, docker/Dockerfile.centos-8, docker/Dockerfile.ubuntu-19.10, docker/Makefile, docker/docker-helper
=> Add CI setup for building published Docker images

hilti/CMakeLists.txt, hilti/include/rt/types/bytes.h, hilti/src/rt/tests/bytes.cc, hilti/src/rt/tests/stream.cc, hilti/src/rt/types/bytes.cc, hilti/src/rt/types/regexp.cc, hilti/src/rt/types/stream.cc, zeek/plugin/include/runtime-support.h
=> Clean up string interface exposed by rt::Bytes

hilti/CMakeLists.txt, hilti/include/rt/types/integer.h, hilti/include/rt/types/string.h, hilti/include/rt/types/vector.h, hilti/src/rt/tests/to_string.cc, spicy/src/compiler/codegen/parser-builder.cc
=> Fixes to stringification

spicy/src/compiler/parser/parser.yy, tests/Baseline/spicy.types.integer.ctor-fail-2/output, tests/Baseline/spicy.types.integer.ctor-fail-3/output, tests/Baseline/spicy.types.integer.ctor-fail-4/output, tests/Baseline/spicy.types.integer.ctor-fail-5/output, tests/Baseline/spicy.types.integer.ctor-fail-6/output, tests/spicy/types/integer/ctor.spicy
=> Allow signs in intX/uintX() constructors.

hilti/include/rt/types/vector.h, hilti/src/rt/tests/vector.cc, tests/hilti/types/vector/ops.hlt
=> Resize eagerly when accessing out-of-bounds Vector elements.

tests/Baseline/zeek.evt.port-fail-2/output, tests/Baseline/zeek.evt.port-fail/output, tests/zeek/evt/port-fail.evt, zeek/compiler/glue-compiler.cc
=> Add range check to port parsing in EVT files.

spicy/src/compiler/visitors/validator.cc, tests/Baseline/spicy.types.unit.parseable-fail/output, tests/spicy/types/unit/parseable-fail.spicy
=> Validate that unit fields have parseable types.

3rdparty/justrx/src/ccl.c, 3rdparty/justrx/src/dfa-interpreter-min.c, 3rdparty/justrx/src/dfa-interpreter-std.c, 3rdparty/justrx/src/jrx.c, 3rdparty/justrx/src/re-scan.l, 3rdparty/justrx/test/retest.c, doc/programming/language/types.rst, hilti/src/rt/tests/regexp.cc
We have some signed vs unsigned mismatches in JRX.
=> Fix binary regex matching

hilti/src/compiler/visitors/validator.cc, spicy/src/compiler/codegen/parser-builder.cc, tests/Baseline/hilti.validation.declaration-cycle/output, tests/Baseline/spicy.types.unit.conditional-parse-at/output, tests/hilti/validation/declaration-cycle.hlt, tests/spicy/types/unit/conditional-parse-at.spicy
=>  Fix duplicate evaluation of if-condition when used with &parse-at.

.cirrus.yml, ci/run-ci
Adapting to Cirrus' changes in limits.
=> Reduce resources requested from Cirrus.

hilti/include/ast/types/computed.h, hilti/include/ast/types/struct.h, hilti/include/rt/types/vector.h, hilti/src/ast/node_ref.cc, hilti/src/compiler/codegen/types.cc, hilti/src/compiler/visitors/printer.cc, spicy/include/ast/types/unit-items/field.h, spicy/src/ast/types/unit-items/field.cc, spicy/src/compiler/codegen/codegen.cc, spicy/src/compiler/codegen/grammar-builder.cc, spicy/src/compiler/codegen/parser-builder.cc, spicy/src/compiler/codegen/unit-builder.cc, spicy/src/compiler/visitors/id-resolver.cc, tests/Baseline/spicy.types.vector.parse-enum/output, tests/spicy/types/vector/parse-enum.spicy
=> Fix &convert with vectors.

doc/autogen/spicy-functions.spicy, doc/scripts/autogen-spicy-lib
=> Fix autogen-spicy-lib to extract multi-line comments.

hilti/include/rt/extension-points.h, hilti/include/rt/iterator.h, hilti/include/rt/types/bytes.h, hilti/include/rt/types/list.h, hilti/include/rt/types/map.h, hilti/include/rt/types/set.h, hilti/include/rt/types/stream.h, hilti/include/rt/types/vector.h, hilti/src/compiler/codegen/operators.cc, hilti/src/compiler/codegen/statements.cc, hilti/src/rt/tests/stream.cc, hilti/src/rt/tests/to_string.cc, hilti/src/rt/tests/vector.cc, hilti/src/rt/types/regexp.cc, hilti/src/rt/types/stream.cc, spicy/src/rt/driver.cc, spicy/src/rt/parser.cc, spicy/src/rt/sink.cc
=> Make stream-related iterators safe by default

doc/programming/language/statements.rst, doc/programming/language/types.rst, doc/programming/parsing.rst, doc/tutorial/examples/_rrq.spicy.output_2, doc/tutorial/index.rst
=> Addressing feedback for tutorial and adding short "Next Steps" section.

hilti/src/compiler/codegen/operators.cc, tests/spicy/types/time/ops.spicy
=> Add codegen for Spicy time difference.

hilti/include/compiler/detail/cxx/unit.h, hilti/src/compiler/cxx/unit.cc, tests/spicy/lib/protocols/dns/prototypes.test, tests/spicy/lib/protocols/http/prototypes.test
This got out of sync with the standard code generator. Refactored now
to share the same code.
Closes #429.
=> Fix generation of C++ prototypes for host applications.

hilti/include/ast/declarations/constant.h, hilti/src/ast/expressions/id.cc, hilti/src/compiler/codegen/codegen.cc, hilti/src/compiler/parser/parser.yy, hilti/src/compiler/visitors/apply-coercions.cc, hilti/src/compiler/visitors/printer.cc, spicy/src/compiler/parser/parser.yy, tests/hilti/types/integer/coercion.hlt, tests/spicy/types/integer/coercion.spicy
=> Add support for declaring constants with explicit types.

tests/hilti/types/time/functions.hlt
=> Extend a test's life time by 10 years.

spicy/src/rt/parser.cc
=> Fix potential invalid iterator deref in debug output.

.cirrus.yml, .clang-tidy, hilti/CMakeLists.txt, hilti/include/rt/debug-logger.h, hilti/include/rt/iterator.h, hilti/include/rt/safe-int.h, hilti/include/rt/types/bytes.h, hilti/src/rt/backtrace.cc, hilti/src/rt/tests/backtrace.cc, hilti/src/rt/tests/configuration.cc, hilti/src/rt/tests/debug-logger.cc, hilti/src/rt/tests/iterator.cc, hilti/src/rt/tests/safe-int.cc
This patchset is part of #468.
=> Tests for hilti/rt/{backtrace.h,iterator.h,safe-int.h,configuration.h,debug-logger.h}

.cirrus.yml, ci/Makefile, ci/run-ci, docker/Dockerfile.alpine-3.11, docker/Dockerfile.centos-8, docker/Dockerfile.ubuntu-19.10, zeek/plugin/src/plugin.cc
Also factoring out the package config in cirrus.yml and Dockerfiles.
=> Switch current Zeek packages to 3.2-rc.

.cirrus.yml, ci/Dockerfile, ci/run-ci, hilti/CMakeLists.txt, hilti/include/ast/node_ref.h, hilti/include/rt/backtrace.h, hilti/include/rt/context.h, hilti/include/rt/deferred-expression.h, hilti/include/rt/exception.h, hilti/include/rt/fiber.h, hilti/include/rt/library.h, hilti/src/rt/library.cc, hilti/src/rt/tests/backtrace.cc, hilti/src/rt/tests/config.h.in, hilti/src/rt/tests/context.cc, hilti/src/rt/tests/debug-logger.cc, hilti/src/rt/tests/deferred-expression.cc, hilti/src/rt/tests/exception.cc, hilti/src/rt/tests/library-dummy.cc, hilti/src/rt/tests/library.cc, hilti/src/rt/util.cc
This patchset is part of #468.
=> Extend tests of hilti/rt/{context,deferred-expression,exception,library}.h

CMakeLists.txt, spicy/CMakeLists.txt, spicy/include/rt/base64.h, spicy/include/rt/sink.h, spicy/src/rt/base64.cc, spicy/src/rt/tests/base64.cc, spicy/src/rt/tests/debug.cc, spicy/src/rt/tests/main.cc
=> Extend unit test coverage of spicy-rt

spicy/CMakeLists.txt, spicy/include/rt/mime.h, spicy/include/rt/parsed-unit.h, spicy/include/rt/zlib.h, spicy/src/rt/tests/global-state.cc, spicy/src/rt/tests/mime.cc, spicy/src/rt/tests/parsed-unit.cc, spicy/src/rt/tests/util.cc, spicy/src/rt/tests/zlib.cc, spicy/src/rt/zlib.cc
This patchset is part of #468.
=> Add unit tests for spicy/rt/{global-state,util,mime,parsed-unit,zlib}.h

spicy/CMakeLists.txt, spicy/include/rt/filter.h, spicy/include/rt/init.h, spicy/include/rt/parser.h, spicy/src/rt/init.cc, spicy/src/rt/parser.cc, spicy/src/rt/tests/init.cc, spicy/src/rt/tests/parser.cc, tests/Baseline/spicy.tools.spicy-driver-batch/.stderr
This patchset is part of #468.
=> Add tests for spicy/rt/{init,parser}.h

zeek/plugin/include/cookie.h, zeek/plugin/include/file-analyzer.h, zeek/plugin/include/plugin.h, zeek/plugin/include/protocol-analyzer.h, zeek/plugin/include/runtime-support.h, zeek/plugin/include/zeek-compat.h, zeek/plugin/include/zeek-reporter.h, zeek/plugin/spicy/zeek_rt.hlt, zeek/plugin/src/file-analyzer.cc, zeek/plugin/src/plugin.cc, zeek/plugin/src/protocol-analyzer.cc, zeek/plugin/src/runtime-support.cc, zeek/plugin/src/zeek-reporter.cc
No CI integration for now because Zeek master is a moving target and officially remains unsupported.
=> Port Zeek plugin to current Zeek master.

doc/examples/_usage-spicyc.output, hilti/toolchain/src/compiler/driver.cc
=> Fix issues in some user-visable strings

hilti/runtime/include/types/bytes.h, hilti/runtime/include/types/reference.h, hilti/runtime/include/types/stream.h, hilti/runtime/src/tests/bytes.cc, hilti/runtime/src/tests/stream.cc, hilti/runtime/src/types/bytes.cc, hilti/runtime/src/types/stream.cc
=> Change `Stream::data` to return `Bytes`.

.cirrus.yml, CMakeLists.txt, docker/Dockerfile.centos-8, docker/Dockerfile.ubuntu-19.10, hilti/runtime/src/tests/util.cc, tests/spicy/types/unit/trimming.spicy
=> Add a CI master step to validate Homebrew formula works.

.cirrus.yml, ci/Dockerfile
=> Add llvm-11 task to Cirrus CI.

hilti/runtime/include/library.h, hilti/runtime/src/library.cc, hilti/runtime/src/tests/library.cc, hilti/toolchain/include/compiler/detail/clang.h, hilti/toolchain/include/compiler/driver.h, hilti/toolchain/include/compiler/jit.h, hilti/toolchain/src/compiler/clang.cc, hilti/toolchain/src/compiler/driver.cc, hilti/toolchain/src/compiler/jit.cc, tests/spicy/doc/my-http-host-driver-hlto.cc, zeek/plugin/include/plugin.h, zeek/plugin/src/plugin.cc
=> Do not copy libraries on JIT or loading

.cirrus.yml, docker/Dockerfile.centos-7, docker/Makefile, docker/docker-helper, hilti/toolchain/src/compiler/codegen/ctors.cc, hilti/toolchain/src/compiler/visitors/printer.cc
=> Add CI job for centos7

doc/development/benchmarking.rst, doc/development/index.rst, hilti/runtime/include/fiber.h, hilti/runtime/src/fiber.cc, hilti/runtime/src/tests/fiber.cc, scripts/run-benchmarks, spicy/runtime/include/driver.h, spicy/runtime/src/driver.cc, spicy/runtime/src/zlib.cc, spicy/toolchain/CMakeLists.txt, spicy/toolchain/bin/spicy-batch-extract.cc, zeek/plugin/include/file-analyzer.h, zeek/plugin/include/packet-analyzer.h, zeek/plugin/include/protocol-analyzer.h, zeek/plugin/src/file-analyzer.cc, zeek/plugin/src/packet-analyzer.cc, zeek/plugin/src/protocol-analyzer.cc
The script isn't perfect yet, but will do the job for now. No need to review in detail.
I added documentation on how to use it to the Developer's manual. I also prepared a preprocessed archive with test data, generated from the Zeek external test suite traces. Need to upload that somewhere still, it's pretty large.
This PR also includes fixes for a couple of regressions (functionality & performance). We remain a bit slower still than Zeek (we used to be closer), but nothing obviously broken sticks out in the perf output at least.
=> Merge the benchmarking script

spicy/toolchain/CMakeLists.txt, spicy/toolchain/include/compiler/detail/codegen/productions/while.h, spicy/toolchain/src/compiler/codegen/grammar-builder.cc, spicy/toolchain/src/compiler/codegen/parser-builder.cc, spicy/toolchain/src/compiler/codegen/productions/while.cc
No test for the problem we used to have as I'm not sure how to test for that reliably (we'd need to trigger stack overflow)
=> Redo parsing of look-ahead vectors

hilti/runtime/src/tests/intrusive-ptr.cc
=> Add unit tests for IntrusivePtr.

.cirrus.yml, ci/Dockerfile, ci/Dockerfile.packages, docker/Dockerfile.centos-7, docker/Dockerfile.centos-8, docker/Dockerfile.ubuntu-19.10, hilti/runtime/src/library.cc, hilti/toolchain/src/compiler/cxx/unit.cc, spicy/runtime/include/driver.h, spicy/runtime/src/driver.cc, tests/zeek/lib/protocols/http.zeek, zeek/plugin/include/file-analyzer.h, zeek/plugin/include/protocol-analyzer.h, zeek/plugin/include/runtime-support.h, zeek/plugin/spicy/zeek_rt.hlt, zeek/plugin/src/file-analyzer.cc, zeek/plugin/src/protocol-analyzer.cc, zeek/plugin/src/runtime-support.cc
=> Install Zeek from packages.

doc/autogen/types/stream-view.rst, doc/programming/debugging.rst, doc/programming/language/statements.rst, doc/programming/language/types.rst, doc/programming/parsing.rst, hilti/toolchain/include/ast/operators/stream.h
This fixes the remaining issues reported in #441.
=> Documentation cleanup

.lgtm.yml
=> Add LGTM config file.

.cirrus.yml, ci/prepare_freebsd.sh, tests/zeek/evt/optional.zeek
=> Add FreeBSD to the CI

hilti/toolchain/src/compiler/clang.cc
Started to need this after upgrading to Big Sur. Should be fine
elsewhere too, but CI will tell us ...
=> Fix for macOS 10.16.

.cirrus.yml, ci/prepare_freebsd.sh, hilti/toolchain/bin/hilti-config.cc, hilti/toolchain/include/base/logger.h, hilti/toolchain/src/base/logger.cc, hilti/toolchain/src/config.cc.in, spicy/toolchain/bin/spicy-config.cc, tests/hilti/hiltic/cc/separate-units.hlt, tests/spicy/doc/my-http-host-driver-hlto.cc
=> Fix loading of libhilti on freebsd-11

.github/workflows/create-release.yml
This is a fixup commit for 8ae90064a3b28db848f581c23b88248eb6e8125a.
=> Fixes to release pipeline

docker/Dockerfile.centos-7
This part was accidentally committed commented out.
=> Actually build Spicy in centos-7 docker image.

.pre-commit-config.yaml, ci/cron/README, ci/cron/spicy-benchmark.sh, ci/cron/update_spicy_dockerhub.sh
=> Add scripts for nightly benchmarking.

.cirrus.yml
=> Add master CI task for macOS BigSur.

doc/autogen/spicy-functions.spicy, hilti/runtime/include/util.h, hilti/runtime/src/tests/util.cc, hilti/runtime/src/util.cc, spicy/lib/spicy.spicy, tests/spicy/rt/time_formatting.spicy
=> Add strptime Spicy library function.

hilti/toolchain/src/compiler/parser/parser.yy, spicy/toolchain/src/compiler/parser/parser.yy, tests/hilti/types/enum/basic.hlt, tests/spicy/types/enum/type.spicy
=> Allow trailing ',' in enum declarations.

hilti/CMakeLists.txt, hilti/toolchain/src/base/util.cc, hilti/toolchain/src/config.cc.in
=> Bump pathfind.

spicy/toolchain/src/compiler/parser/parser.yy, tests/spicy/types/tuple/operators.spicy
=> Allow trailing comma in tuple type list.

hilti/toolchain/src/compiler/codegen/operators.cc, hilti/toolchain/src/compiler/visitors/apply-coercions.cc, tests/spicy/types/vector/operators.spicy
=> Fix method argument type deduction for argument packs.

docker/Dockerfile.alpine-3.12, docker/Dockerfile.centos-7, docker/Dockerfile.centos-8, docker/Dockerfile.fedora-32, docker/Dockerfile.fedora-33, docker/Dockerfile.ubuntu-16, docker/Dockerfile.ubuntu-18, docker/Dockerfile.ubuntu-20
=> Do not set ZEEK_PLUGIN_PATH in Docker images.

spicy/toolchain/src/compiler/codegen/parser-builder.cc, tests/Baseline/spicy.types.unit.field-max-size/output, tests/Baseline/spicy.types.unit.unit-max-size/output, tests/spicy/types/unit/field-max-size.spicy, tests/spicy/types/unit/unit-max-size.spicy
=> Fix &max-size with constant argument.

doc/programming/examples.rst, doc/programming/examples/_unit-params-vector.spicy, doc/programming/parsing.rst
This PR bumps all submodules and performs a small doc fix for https://github.com/zeek/spicy/issues/817#issuecomment-790924225.
=> Bump dependencies and update docs

.cirrus.yml, .github/workflows/create-release.yml, CMakeLists.txt, configure, doc/installation.rst, docker/Dockerfile.centos-7, docker/Dockerfile.centos-8, docker/Dockerfile.debian-9, docker/Dockerfile.fedora-32, docker/Dockerfile.fedora-33, docker/Dockerfile.ubuntu-16, docker/Dockerfile.ubuntu-18, docker/Dockerfile.ubuntu-20, docker/docker-helper, tests/Makefile
=> Distribute Linux binary artifacts as deb or rpm files

hilti/toolchain/include/ast/node.h, hilti/toolchain/include/ast/types/function.h, hilti/toolchain/include/ast/types/struct.h, hilti/toolchain/src/ast/scope.cc, hilti/toolchain/src/ast/types/enum.cc, hilti/toolchain/src/compiler/context.cc, hilti/toolchain/src/compiler/cxx/elements.cc, hilti/toolchain/src/compiler/cxx/linker.cc, hilti/toolchain/src/compiler/plugin.cc, scripts/autogen-dispatchers, scripts/autogen-type-erased, spicy/toolchain/src/compiler/codegen/parser-builder.cc
=> Fix some issues diagnosed by LGTM.

ci/run-ci, doc/Doxyfile
=> Cleanup for docs build.

doc/autogen/types/bytes.rst, doc/autogen/types/map.rst, doc/autogen/types/set.rst, doc/autogen/types/stream-view.rst, doc/scripts/spicy-doc-to-rst, hilti/toolchain/include/ast/operator.h, hilti/toolchain/src/compiler/parser/parser.yy, hilti/toolchain/src/compiler/parser/scanner.ll, spicy/toolchain/src/compiler/parser/parser.yy, spicy/toolchain/src/compiler/parser/scanner.ll, tests/hilti/types/bytes/ops.hlt, tests/hilti/types/map/ops.hlt, tests/hilti/types/network/ops.hlt, tests/hilti/types/set/ops.hlt
=> Add `!in` to HILTI and Spicy parser.

hilti/runtime/src/library.cc
On macOS ARM, there are odd crashes when loading an HLTO if we created it
by writing over an already existing HLTO file when. Fixing by always removing
existing any files first.
=> Fix crash on macOS ARM when writing over an existing HLTO file.

.clang-tidy.ignore, .pre-commit-config.yaml, scripts/run-clang-format, tests/Baseline/spicy.lib.protocols.dns.single/output
Catching up on spicy-plugin and spicy-analyzers.
=> Updating submodules

.cirrus.yml, docker/Dockerfile.opensuse-15.2, hilti/runtime/include/types/enum.h, hilti/toolchain/include/compiler/unit.h
=> Add opensuse-15.2 to CI.

cmake/Util.cmake
We previsouly were only updating the files at configure time. This
caused issues during development where the code used to generate parsers
came out of sync with the actual parser definitions.
We now properly model the dependency through a custom command which
ensures that preprocessing is kicked off whenever the input changes.
Closes #920.
=> Track patching of Bison files through proper dependencies.

.cirrus.yml, scripts/autogen-version, scripts/make-tarball.sh
=> Fix release tarball

.cirrus.yml, .clang-tidy, ci/Dockerfile, ci/run-ci, hilti/runtime/include/intrusive-ptr.h, hilti/runtime/include/types/integer.h, hilti/toolchain/include/ast/node.h, hilti/toolchain/include/base/intrusive-ptr.h, spicy/toolchain/src/compiler/codegen/parsers/literals.cc, spicy/toolchain/src/compiler/codegen/parsers/types.cc
=> Update CI to clang-tidy-12

hilti/toolchain/src/base/util.cc
=> Make detection of current executable more robust.

CMakeLists.txt, scripts/autogen-version
=> Fix issues around generating version information.

doc/programming/examples/_unit-vars-init.spicy, doc/programming/examples/_unit-vars-init.spicy.output, doc/programming/parsing.rst
=> Document initializers for unit variables.

hilti/toolchain/src/compiler/codegen/codegen.cc, hilti/toolchain/src/compiler/codegen/statements.cc, hilti/toolchain/src/compiler/codegen/types.cc, hilti/toolchain/src/compiler/cxx/elements.cc, hilti/toolchain/src/compiler/cxx/unit.cc, tests/Baseline/hilti.hiltic.print.globals/output, tests/Baseline/hilti.hiltic.print.import/output, tests/Baseline/hilti.types.real.nops/output, tests/hilti/codegen/globals-deps.hlt
=> Declare types used in globals before using them.

doc/programming/language/types.rst
=> Add TODO to docs on unit initialization via list coercion.

doc/zeek.rst
This goes along with https://github.com/zeek/spicy-plugin/pull/78.
=> Update documentation for the plugin's new `$packet`.

.cirrus.yml, CMakeLists.txt, NEWS.rst, ci/run-ci, configure, doc/toolchain.rst, hilti/toolchain/src/config.cc.in
=> Decouple whether Spicy was build with ccache from ccache use during JIT.

ci/run-ci, doc/Makefile
=> Check in CI whether Zeek docs are up-to-date

.pre-commit-config.yaml, .typos.toml, CHANGES, doc/programming/parsing.rst, hilti/runtime/include/types/bytes.h, hilti/runtime/include/types/vector.h, hilti/runtime/src/tests/library.cc, hilti/runtime/src/tests/regexp.cc, hilti/runtime/src/tests/stream.cc, hilti/runtime/src/tests/util.cc, hilti/toolchain/include/ast/node.h, hilti/toolchain/include/ast/operator.h, hilti/toolchain/src/compiler/codegen/types.cc, hilti/toolchain/src/compiler/cxx/elements.cc, hilti/toolchain/src/compiler/cxx/unit.cc, hilti/toolchain/src/compiler/jit.cc, hilti/toolchain/src/compiler/optimizer.cc, spicy/runtime/src/driver.cc, spicy/runtime/src/parser.cc, spicy/runtime/src/sink.cc, spicy/runtime/src/tests/parser.cc, spicy/toolchain/src/compiler/codegen/unit-builder.cc
=> Bump submodules and pre-commit hooks

doc/requirements.txt
This just copies the fix also used in the Zeek docs.
=> Fix styling of lists on RTD.

hilti/runtime/CMakeLists.txt, hilti/runtime/src/tests/intrusive-ptr.cc, spicy/runtime/src/init.cc
=> Fix diagnostics when building with GCC

doc/installation.rst
=> Switch to ECR images in documentation [skip CI].

hilti/toolchain/include/ast/location.h, hilti/toolchain/include/ast/meta.h, hilti/toolchain/include/ast/node-ref.h, hilti/toolchain/include/ast/scope.h, hilti/toolchain/src/ast/meta.cc, hilti/toolchain/src/ast/scope.cc, hilti/toolchain/src/compiler/visitors/normalizer.cc, hilti/toolchain/src/compiler/visitors/validator.cc
=> Optimize AST build throughput

CMakeLists.txt, ci/fuzz/CMakeLists.txt, hilti/runtime/include/config.h.in, hilti/runtime/include/fiber.h, hilti/runtime/include/util.h, hilti/runtime/src/fiber.cc, hilti/runtime/src/tests/util.cc, hilti/toolchain/include/config.h.in, hilti/toolchain/src/config.cc.in, hilti/toolchain/src/global.cc, spicy/toolchain/src/config.cc.in, tests/Scripts/have-sanitizer
=> Make sanitizer features more granular

.cirrus.yml, doc/installation.rst, docker/Dockerfile.fedora-35, docker/Dockerfile.fedora-36, hilti/toolchain/src/compiler/unit.cc
=> Remove potential use-after-move

.cirrus.yml, ci/prepare_freebsd.sh
=> Update CI to freebsd-13.1.

doc/zeek.rst
This covers https://github.com/zeek/spicy-plugin/pull/141.
=> Documentation updates for recent Zeek integration changes.

doc/conf.py, doc/programming/examples/_mylibrary.spicy.output, doc/programming/examples/_rot13.spicy, doc/programming/examples/_rot13.spicy.output, doc/programming/examples/mylibrary.cc, doc/programming/examples/mylibrary.spicy, doc/programming/extending.rst, doc/programming/index.rst, doc/scripts/spicy.py
=> Document how to pull custom C++ code into Spicy.

ci/fuzz/CMakeLists.txt
This PR updates our fuzzing setup both for changes in oss-fuzz as well as in our own dependencies.
=> Update fuzzing setup

hilti/runtime/include/logging.h, hilti/runtime/include/util.h, spicy/runtime/src/parser.cc
=> Fix pathological performance for `_haveEod` on highly chunked streams

spicy/runtime/src/parser.cc
Currently `printParserState` is called at least during synchronization. Previously it would always comput its log message, even if that string was never logged. Since computing this log message involved string formatting it came with a noticable performance penalty.
With this patch we only compute the log message if it would actually be logged using our debug log macros.
=> Make `printParserState` cheaper to call if debug logging is disabled.

.gitmodules, hilti/runtime/include/types/stream.h, hilti/toolchain/include/ast/ctors/interval.h, hilti/toolchain/include/ast/ctors/time.h
This pulls in https://github.com/dcleblanc/SafeInt/pull/50.
=> Switch SafeInt back to upstream.

.cirrus.yml, 3rdparty/CMakeLists.txt, hilti/runtime/include/intrusive-ptr.h, hilti/toolchain/include/ast/operators/generic.h, hilti/toolchain/include/ast/operators/tuple.h, hilti/toolchain/src/compiler/driver.cc, hilti/toolchain/src/compiler/jit.cc, hilti/toolchain/src/compiler/optimizer.cc, hilti/toolchain/src/compiler/unit.cc, hilti/toolchain/src/compiler/visitors/renderer.cc, hilti/toolchain/src/compiler/visitors/resolver.cc, spicy/toolchain/include/compiler/detail/codegen/parser-builder.h, tests/hilti/statements/assert.hlt
This is a companion patch to #1433 for Spicy's LTS release.
=> Fixes for building with gcc13 (LTS)

hilti/runtime/include/exception.h, hilti/runtime/src/exception.cc, tests/spicy/types/sink/parse-error.spicy
This is to measure how often they are instantiated. We ignore
execution time.
=> Profile exception activity.

doc/zeek.rst
This goes with https://github.com/zeek/zeek/pull/3228.
=> Add documentation for `export` extensions.

hilti/runtime/include/types/bitfield.h, hilti/toolchain/src/compiler/codegen/ctors.cc
This lets C++ templates test if a class T is a bitfield.
Needed for upcoming Zeek-side PR.
=> Add trait class to bitfield types.

spicy/toolchain/include/compiler/detail/codegen/parser-builder.h, spicy/toolchain/src/compiler/codegen/parser-builder.cc, spicy/toolchain/src/compiler/codegen/unit-builder.cc, tests/Baseline/spicy.types.unit.synchronize-on-gap/output, tests/spicy/optimization/random-access.spicy
=> Add feature guards to accesses of a unit's `__position`

hilti/runtime/include/fiber-check-stack.h, hilti/runtime/src/fiber.cc
=> Fix new ASAN warnings in `fiber.cc`

hilti/runtime/include/types/stream.h, hilti/runtime/src/tests/stream.cc, hilti/runtime/src/types/stream.cc
@bbannier - here's some commits. For some pcap and parser combination I've tested with, this removes an addition ~5% relative to your branch - probably won't translate.
Pick what makes sense to you. Feel free to redo commits as you see fit and then close this PR :-)
=> Replace Chunk's variant with std::string

.cirrus.yml
- Bump justrx to pull in bugfix.
- CI: Re-enable `clang17_ubuntu_debug_task`.
=>  Bump justrx to pull in bugfix.

.cirrus.yml, docker/Dockerfile.debian-12, docker/Dockerfile.fedora-39, docker/Dockerfile.opensuse-15.5
This bumps all CI setups to b465b010e7c56ec62152e75d96fad4e761e49360.
=> Refresh CI for 1.10 release branch

hilti/toolchain/src/ast/ast-context.cc
If a 3rdparty (like Zeek) still retains a pointer to a Node, the check
would trigger, making usage awkward. Instead we now just check at
context destruction time that we no longer have any live nodes.
=> Do not require all AST nodes to be destroyed before we begin compilation.

doc/conf.py
This hadn't been updated in a while, leading to outdated links.
=> Update release in documentation.

doc/conf.py, doc/installation.rst, doc/programming/language/error-handling.rst, doc/programming/language/statements.rst
This feature is not on the horizon and having it documented prominently
painted an incorrect picture for users. Drop its docs for now until we
actually provide it.
=> Drop docs around try/catch

.cirrus.yml, CMakeLists.txt, docker/Dockerfile.ubuntu-24, hilti/runtime/include/types/integer.h, hilti/runtime/include/types/map.h, hilti/runtime/src/tests/fiber.cc, hilti/toolchain/CMakeLists.txt, hilti/toolchain/src/compiler/codegen/statements.cc, hilti/toolchain/src/compiler/jit.cc, hilti/toolchain/src/compiler/optimizer.cc, hilti/toolchain/src/config.cc.in, scripts/precompile-headers.sh, spicy/runtime/src/parser.cc
Found while trying to test something with EXTRA_CXX_FLAGS. This got lost in e27cd5ac0443659e7e9fdae2f3bbe5920bd3564b.
=> Fix --enable-werror werror_flags.

doc/autogen/types/enum.rst, doc/autogen/types/generic-new.rst, doc/autogen/types/generic.rst, hilti/toolchain/src/ast/operators/enum.cc, hilti/toolchain/src/ast/operators/generic.cc
🤷 
(I didn't go through every case, I just grepped for "it's type")
=> Fix "it's" used as a possessive

doc/autogen/types/generic-new.rst, doc/autogen/types/generic.rst, doc/programming/parsing.rst, hilti/toolchain/src/ast/operators/generic.cc
=> Document arguments to `new` operator.

spicy/toolchain/src/compiler/codegen/parsers/literals.cc, tests/spicy/types/integer/parse-coerced-ctor.spicy
=> Fix the literals parsers not following coercions.

README.md
=> Audit links in README [skip CI]

3rdparty/CMakeLists.txt
This pulls in https://github.com/rsmmr/justrx/pull/12.
=> Bump justrx to pull in CCL speed-up.

hilti/toolchain/include/compiler/detail/cxx/unit.h, hilti/toolchain/src/compiler/cxx/unit.cc, tests/Baseline/hilti.types.tuple.coercion/output, tests/spicy/types/type/type-info.spicy
=> Ensure generated typeinfos are declared before used.

hilti/toolchain/include/ast/declarations/field.h
(Forgot to commit this earlier.)
=> Remove stale code.

doc/autogen/architecture.svg
Seeing some changes locally due to, I presume, some update of the
toolchain generating the diagram. Let's see if this passes CI.
=> Update architecture diagram.

hilti/runtime/include/type-info.h, hilti/toolchain/src/compiler/codegen/types.cc, tests/hilti/codegen/type-info.hlt
- **Fix unit test for bitfields.**
- **Add bit ranges to type information for bitfields.**
=> Add bit ranges to type information for bitfields.

hilti/runtime/include/type-info.h, hilti/runtime/src/tests/type-info.cc, hilti/toolchain/src/compiler/codegen/types.cc
So far a host application couldn't learn about any fields in a HILTI
`struct` that, although defined by the HILTI type, were skipped from
the C++ struct generated by the codegen (e.g., because it's anonymous
and hence won't receive a value anyways). Now we include these fields
into the struct's type information as well, so that they can still be
discovered during introspection. The field's type information gains a
new flag for querying whether it has been emitted. However, when
iterating a struct's field *values* (in constrast to its field
*types*) we continue to skip these fields since they don't have a
value after all. This also means that existing host applications
shouldn't run into any trouble when iterating the values, nothing
changes there.
=> Include all fields into a struct's type information, even if not emitted.

hilti/runtime/src/fiber.cc
Our fiber code could trigger ASAN to report a false positive: If a
block of memory had already been used before as stack memory for a
previously existing fiber, that usage may have left ASAN guard regions
in place reflecting the state when that old fiber finished. If we were
now reusing the same memory for a new fiber's stack, ASAN would
continue to check any accesses against that old state. So when this
memory now got reinitialized with a new stack structure (i.e.,
essentially writing to arbitrary locations inside the block), those
writes could trigger ASAN to report an out-of-bounds access.
This triggered on ARM, but could have just as well triggered in x86 as
well. I think it was just by chance that x86 ended up working.
=> Fix ASAN false positive on ARM.
